$axure.loadCurrentPage({
  "url":"移车完成.html",
  "generationDate":new Date(1503998487941.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"jvbao",
"yiche",
"mianfenquan"],
  "page":{
    "packageId":"0fac9111a83842139292301570dbc846",
    "type":"Axure:Page",
    "name":"移车完成",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"250bd29c4a4946cc89d5c9d4f34e2a1c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":647}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"590ca7b466cf422fa9fe093b90eb0a34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":647}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/移车完成/u0.jpg"}},
{
          "id":"2a58d7cad2054d369bd4940d15380eaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":90,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9eab58a3afd84be4bef5c3a5c61004f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":90,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 自助移车",
                      "target":{
                        "targetType":"page",
                        "url":"自助移车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"545f76f4e0234e2fbb751d28b7e88d49",
          "label":"确认按钮",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "verticalAlignment":"top",
            "lineSpacing":"28px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "paddingTop":"15",
            "location":{
              "x":0,
              "y":40},
            "size":{
              "width":380,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5514881a6c874619b3c572a0cca06910",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "verticalAlignment":"top",
                "lineSpacing":"28px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "paddingTop":"15",
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":380,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/移车完成/确认按钮_u4.png"}},
{
          "id":"7aa86f7e0f4945af87d7b27360db831a",
          "label":"确认按钮",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "lineSpacing":"28px",
            "paddingTop":"15",
            "location":{
              "x":130,
              "y":5},
            "size":{
              "width":120,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1e74c663b1d4d0d85473980b6ebb79f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "lineSpacing":"28px",
                "paddingTop":"15",
                "location":{
                  "x":130,
                  "y":5},
                "size":{
                  "width":120,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/移车完成/确认按钮_u6.png"}},
{
          "id":"c85ffc71e6064ca2a3adcd4a3e88603c",
          "label":"确认按钮",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "verticalAlignment":"top",
            "lineSpacing":"28px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "paddingTop":"15",
            "location":{
              "x":34.5,
              "y":250},
            "size":{
              "width":306,
              "height":130},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01d31cdd15ac4d5ebc089982b5e494b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "verticalAlignment":"top",
                "lineSpacing":"28px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "paddingTop":"15",
                "location":{
                  "x":34.5,
                  "y":250},
                "size":{
                  "width":306,
                  "height":130},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/移车完成/确认按钮_u8.png"}},
{
          "id":"e07795d23cef446aa4a383cc2adc1c4d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":120},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14876f8ca3aa42979197e54cd49b29c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":135,
                  "y":120},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/移车完成/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "250bd29c4a4946cc89d5c9d4f34e2a1c":{
      "scriptId":"u0"},
    "590ca7b466cf422fa9fe093b90eb0a34":{
      "scriptId":"u1"},
    "2a58d7cad2054d369bd4940d15380eaf":{
      "scriptId":"u2"},
    "9eab58a3afd84be4bef5c3a5c61004f6":{
      "scriptId":"u3"},
    "545f76f4e0234e2fbb751d28b7e88d49":{
      "scriptId":"u4"},
    "5514881a6c874619b3c572a0cca06910":{
      "scriptId":"u5"},
    "7aa86f7e0f4945af87d7b27360db831a":{
      "scriptId":"u6"},
    "b1e74c663b1d4d0d85473980b6ebb79f":{
      "scriptId":"u7"},
    "c85ffc71e6064ca2a3adcd4a3e88603c":{
      "scriptId":"u8"},
    "01d31cdd15ac4d5ebc089982b5e494b3":{
      "scriptId":"u9"},
    "e07795d23cef446aa4a383cc2adc1c4d":{
      "scriptId":"u10"},
    "14876f8ca3aa42979197e54cd49b29c9":{
      "scriptId":"u11"}}});