$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1503998485703.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"jvbao",
"yiche",
"mianfenquan"],
  "page":{
    "packageId":"06a649b85ad84487ae8033bb4de651fc",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1cbc585bd7cc4cbeaaa74a8f77901729",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"99b936d41aee4c9eab953b31e7454d12",
              "label":"驾驶证业务",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"cad154f1db974af0ad7b43a9ca8a7a8e",
                  "label":"9",
                  "parentDynamicPanel":"1cbc585bd7cc4cbeaaa74a8f77901729",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":647}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"634ca19287c24f6dbfda306080ce6188",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1cbc585bd7cc4cbeaaa74a8f77901729",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":375,
                          "height":647}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/9_u1.png"}},
{
                  "id":"f9dec202a5d94f85be48f3209778ce65",
                  "label":"8",
                  "parentDynamicPanel":"1cbc585bd7cc4cbeaaa74a8f77901729",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":70,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dcb96dc7ff8b4af198211b502065af9c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1cbc585bd7cc4cbeaaa74a8f77901729",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":70,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0080049e55fc43d38d5a3a7ea85df575",
                  "label":"e大厅2",
                  "parentDynamicPanel":"1cbc585bd7cc4cbeaaa74a8f77901729",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":598},
                    "size":{
                      "width":124,
                      "height":49},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0cb0c256e24c400a96f747477fa20287",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1cbc585bd7cc4cbeaaa74a8f77901729",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":598},
                        "size":{
                          "width":124,
                          "height":49},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 范围 to 首页 显示隐藏,<br>(动态面板) to State1 显示隐藏",
                              "panelsToStates":[{
                                  "panelPath":["795e6e78996842f0b5f36decd87220be"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "compress":false}}},
{
                                  "panelPath":["71aefb8876ab43eb8532d9dcf41d80a9"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示 顶部,<br>底部,<br>机动车业务,<br>驾驶证业务,<br>隐藏 (动态面板)",
                              "objectsToFades":[{
                                  "objectPath":["8a73243730cc4620bc3b3070900ffeb9"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["65bb1381a4c546f7a2a3826c764769aa"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["3772e426be7f4eb69207d6739de95e3a"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["8f6e5f7ceb274483a20b2a0c3fe4a8a3"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["1cbc585bd7cc4cbeaaa74a8f77901729"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5241301c30cf497781cc62d3bd2dda05",
                  "label":"机动车业务",
                  "parentDynamicPanel":"1cbc585bd7cc4cbeaaa74a8f77901729",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":127,
                      "y":598},
                    "size":{
                      "width":124,
                      "height":49},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0540d783790942f0a6ddfbc990a66f75",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1cbc585bd7cc4cbeaaa74a8f77901729",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":127,
                          "y":598},
                        "size":{
                          "width":124,
                          "height":49},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 机动车业务 显示隐藏",
                              "panelsToStates":[{
                                  "panelPath":["1cbc585bd7cc4cbeaaa74a8f77901729"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示 (动态面板),<br>2,<br>六年免检,<br>e大厅1,<br>驾驶证业务,<br>1",
                              "objectsToFades":[{
                                  "objectPath":["1cbc585bd7cc4cbeaaa74a8f77901729"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["5ea8f1b5a65e47d181308fb726a3b36e"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["09a636b505c442f38af0ff35e7c37a5b"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["ac7e0d7f0ada45c383aa520d8749e486"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["9673da2b28004154aa19f6bf7e6dd083"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["d8d2c64aab924ce7ba7d7a125dddd6ab"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"59ff4d134d0f416897742e17659e2ac5",
              "label":"机动车业务",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d8d2c64aab924ce7ba7d7a125dddd6ab",
                  "label":"1",
                  "parentDynamicPanel":"1cbc585bd7cc4cbeaaa74a8f77901729",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":647}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b642cfdc3db34e27bc3dcbcc9c2969a9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1cbc585bd7cc4cbeaaa74a8f77901729",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":375,
                          "height":647}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/1_u9.png"}},
{
                  "id":"5ea8f1b5a65e47d181308fb726a3b36e",
                  "label":"2",
                  "parentDynamicPanel":"1cbc585bd7cc4cbeaaa74a8f77901729",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":70,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"502b2edcd8314cb4be4dde51ea36e0d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1cbc585bd7cc4cbeaaa74a8f77901729",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":70,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ac7e0d7f0ada45c383aa520d8749e486",
                  "label":"e大厅1",
                  "parentDynamicPanel":"1cbc585bd7cc4cbeaaa74a8f77901729",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":598},
                    "size":{
                      "width":124,
                      "height":49},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"85b318446de3447d8051dd7137ee629a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1cbc585bd7cc4cbeaaa74a8f77901729",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":598},
                        "size":{
                          "width":124,
                          "height":49},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 范围 to 首页 显示隐藏,<br>(动态面板) to State1 显示隐藏",
                              "panelsToStates":[{
                                  "panelPath":["795e6e78996842f0b5f36decd87220be"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "compress":false}}},
{
                                  "panelPath":["71aefb8876ab43eb8532d9dcf41d80a9"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 (动态面板)",
                              "objectsToFades":[{
                                  "objectPath":["1cbc585bd7cc4cbeaaa74a8f77901729"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示 顶部,<br>底部,<br>机动车业务,<br>驾驶证业务",
                              "objectsToFades":[{
                                  "objectPath":["8a73243730cc4620bc3b3070900ffeb9"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["65bb1381a4c546f7a2a3826c764769aa"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["3772e426be7f4eb69207d6739de95e3a"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["8f6e5f7ceb274483a20b2a0c3fe4a8a3"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9673da2b28004154aa19f6bf7e6dd083",
                  "label":"驾驶证业务",
                  "parentDynamicPanel":"1cbc585bd7cc4cbeaaa74a8f77901729",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":262,
                      "y":598},
                    "size":{
                      "width":113,
                      "height":49},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a8223445bbb64420ab49dc48989886d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1cbc585bd7cc4cbeaaa74a8f77901729",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":262,
                          "y":598},
                        "size":{
                          "width":113,
                          "height":49},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 驾驶证业务 显示隐藏",
                              "panelsToStates":[{
                                  "panelPath":["1cbc585bd7cc4cbeaaa74a8f77901729"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示 (动态面板),<br>9,<br>8,<br>e大厅2,<br>机动车业务",
                              "objectsToFades":[{
                                  "objectPath":["1cbc585bd7cc4cbeaaa74a8f77901729"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["cad154f1db974af0ad7b43a9ca8a7a8e"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["f9dec202a5d94f85be48f3209778ce65"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["0080049e55fc43d38d5a3a7ea85df575"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["5241301c30cf497781cc62d3bd2dda05"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"09a636b505c442f38af0ff35e7c37a5b",
                  "label":"六年免检",
                  "parentDynamicPanel":"1cbc585bd7cc4cbeaaa74a8f77901729",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":85},
                    "size":{
                      "width":374,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dae74f26627f4b63a14523252eaefd1a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1cbc585bd7cc4cbeaaa74a8f77901729",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":85},
                        "size":{
                          "width":374,
                          "height":45},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 六年免检办理及预约",
                              "target":{
                                "targetType":"page",
                                "url":"六年免检办理及预约.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"795e6e78996842f0b5f36decd87220be",
          "label":"范围",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":49},
            "size":{
              "width":375,
              "height":574}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"98f109b319f24fa5bff2a3f490cc44e9",
              "label":"首页",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"71aefb8876ab43eb8532d9dcf41d80a9",
                  "label":"",
                  "parentDynamicPanel":"795e6e78996842f0b5f36decd87220be",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":732}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onDrag":{
                      "description":"OnDrag",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"移动 (动态面板) y 轴拖动",
                              "objectsToMoves":[{
                                  "objectPath":["71aefb8876ab43eb8532d9dcf41d80a9"],
                                  "moveInfo":{
                                    "moveType":"dragY",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 (动态面板)",
                              "objectsToFades":[{
                                  "objectPath":["1cbc585bd7cc4cbeaaa74a8f77901729"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]},
                    "onDragDrop":{
                      "description":"OnDragDrop",
                      "cases":[{
                          "description":"用例 1<br> (If area of This 接触后 area of 底部)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"fcall",
                            "functionName":"IsOver",
                            "arguments":[{
                                "exprType":"fcall",
                                "functionName":"GetWidgetRectangles",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":true,
                                    "isFocused":false,
                                    "isTarget":false}]},
{
                                "exprType":"fcall",
                                "functionName":"GetWidgetRectangles",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["65bb1381a4c546f7a2a3826c764769aa"]}]}]},
                          "actions":[{
                              "action":"moveWidget",
                              "description":"移动 (动态面板) 到 (0,0) 摆动 100ms",
                              "objectsToMoves":[{
                                  "objectPath":["71aefb8876ab43eb8532d9dcf41d80a9"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"swing",
                                      "duration":100}}}]}]},
{
                          "description":"用例 2<br> (Else If area of This 接触后 area of 顶部)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"fcall",
                            "functionName":"IsOver",
                            "arguments":[{
                                "exprType":"fcall",
                                "functionName":"GetWidgetRectangles",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":true,
                                    "isFocused":false,
                                    "isTarget":false}]},
{
                                "exprType":"fcall",
                                "functionName":"GetWidgetRectangles",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["8a73243730cc4620bc3b3070900ffeb9"]}]}]},
                          "actions":[{
                              "action":"moveWidget",
                              "description":"移动 (动态面板) 到 (0,-152) 摆动 100ms",
                              "objectsToMoves":[{
                                  "objectPath":["71aefb8876ab43eb8532d9dcf41d80a9"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-152",
                                      "stos":[]},
                                    "options":{
                                      "easing":"swing",
                                      "duration":100}}}]}]}]}},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"c0a0c98f93e547cf863a70b29f4b5f6a",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"91f48be64cfc4ef28c5c244bb5d3dcf1",
                          "label":"长页内容",
                          "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":373,
                              "height":732},
                            "rotation":"0",
                            "textRotation":"0",
                            "borderWidth":"0",
                            "cornerRadiusTopLeft":"0"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"b578a2d542ee4b3dbba81e9c913270e4",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":373,
                                  "height":732},
                                "rotation":"0",
                                "textRotation":"0",
                                "borderWidth":"0",
                                "cornerRadiusTopLeft":"0"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/首页/长页内容_u21.png"}},
{
                          "id":"fb82337bcae246419a588829ab8ab659",
                          "label":"预约业务",
                          "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0x333333,
                              "opacity":0},
                            "opacity":"0",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":170},
                            "size":{
                              "width":89,
                              "height":86},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0x797979}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"a47b129951534194b21d626bdc412ef8",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0x333333,
                                  "opacity":0},
                                "opacity":"0",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "location":{
                                  "x":0,
                                  "y":170},
                                "size":{
                                  "width":89,
                                  "height":86},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0x797979}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"在 当前窗口 打开 预约业务",
                                      "target":{
                                        "targetType":"page",
                                        "url":"预约业务.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"d5002a76fa384f5da953050ec1c4a37d",
                          "label":"个人中心",
                          "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0x333333,
                              "opacity":0},
                            "opacity":"0",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":279,
                              "y":170},
                            "size":{
                              "width":95,
                              "height":86},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0x797979}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"132cfbdcfc7b4ef097f97309c2452ce8",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0x333333,
                                  "opacity":0},
                                "opacity":"0",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "location":{
                                  "x":279,
                                  "y":170},
                                "size":{
                                  "width":95,
                                  "height":86},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0x797979}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"在 当前窗口 打开 个人中心",
                                      "target":{
                                        "targetType":"page",
                                        "url":"个人中心.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"7400bd1ab059488490db343e9df615c8",
                          "label":"违法举报",
                          "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0x333333,
                              "opacity":0},
                            "opacity":"0",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":303},
                            "size":{
                              "width":89,
                              "height":86},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0x797979}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"0fddf80d42dd4aee8c0d1b1fc843e75f",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0x333333,
                                  "opacity":0},
                                "opacity":"0",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "location":{
                                  "x":0,
                                  "y":303},
                                "size":{
                                  "width":89,
                                  "height":86},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0x797979}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"在 当前窗口 打开 违法举报须知",
                                      "target":{
                                        "targetType":"page",
                                        "url":"违法举报须知.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"8ed436d7d1a14ec4833d584e0be56815",
                          "label":"移车",
                          "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0x333333,
                              "opacity":0},
                            "opacity":"0",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":184,
                              "y":303},
                            "size":{
                              "width":95,
                              "height":86},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0x797979}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"6bac7e410a7e49a6965378e4b69449d2",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0x333333,
                                  "opacity":0},
                                "opacity":"0",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "location":{
                                  "x":184,
                                  "y":303},
                                "size":{
                                  "width":95,
                                  "height":86},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0x797979}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"在 当前窗口 打开 自助移车",
                                      "target":{
                                        "targetType":"page",
                                        "url":"自助移车.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"4086f42bcacd462a8e660ed8d4554abd",
                          "label":"评价",
                          "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0x333333,
                              "opacity":0},
                            "opacity":"0",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":279,
                              "y":303},
                            "size":{
                              "width":95,
                              "height":86},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0x797979}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"c9014b202c5d476ca656a184d02ebe3b",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0x333333,
                                  "opacity":0},
                                "opacity":"0",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "location":{
                                  "x":279,
                                  "y":303},
                                "size":{
                                  "width":95,
                                  "height":86},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0x797979}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"在 当前窗口 打开 网上评价",
                                      "target":{
                                        "targetType":"page",
                                        "url":"网上评价.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"985d292f2982488280b8db42ec80fb01",
                          "label":"叫号",
                          "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0x333333,
                              "opacity":0},
                            "opacity":"0",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":279,
                              "y":497.999969482422},
                            "size":{
                              "width":95,
                              "height":86},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0x797979}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"cb62bc8cd7ee41f7a1f3c2a6b3884759",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0x333333,
                                  "opacity":0},
                                "opacity":"0",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "location":{
                                  "x":279,
                                  "y":497.999969482422},
                                "size":{
                                  "width":95,
                                  "height":86},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0x797979}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"在 当前窗口 打开 办事大厅叫号查询",
                                      "target":{
                                        "targetType":"page",
                                        "url":"办事大厅叫号查询.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"6d6200264d624a6dbf5fbec8651997e7",
                          "label":"驾考在线",
                          "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0x333333,
                              "opacity":0},
                            "opacity":"0",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":646},
                            "size":{
                              "width":89,
                              "height":86},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0x797979}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"d4bc710a1d6b4d97a5b228cdc6518c20",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0x333333,
                                  "opacity":0},
                                "opacity":"0",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "location":{
                                  "x":0,
                                  "y":646},
                                "size":{
                                  "width":89,
                                  "height":86},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0x797979}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"在 当前窗口 打开 驾考在线学习",
                                      "target":{
                                        "targetType":"page",
                                        "url":"驾考在线学习.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"045f2b07fae049809b8dda8d493b89fd",
                          "label":"审验",
                          "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0x333333,
                              "opacity":0},
                            "opacity":"0",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":89,
                              "y":646},
                            "size":{
                              "width":89,
                              "height":86},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0x797979}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"6693e8fd211741e18b19409fad76edac",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0x333333,
                                  "opacity":0},
                                "opacity":"0",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "location":{
                                  "x":89,
                                  "y":646},
                                "size":{
                                  "width":89,
                                  "height":86},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0x797979}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"在 当前窗口 打开 审验学习",
                                      "target":{
                                        "targetType":"page",
                                        "url":"审验学习.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"0f306c6f816d42e0a94952eb67afd20e",
                          "label":"满分",
                          "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0x333333,
                              "opacity":0},
                            "opacity":"0",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":184,
                              "y":646},
                            "size":{
                              "width":95,
                              "height":86},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0x797979}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"9e9a59d0c4614a2097a1352cb27e2a6e",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0x333333,
                                  "opacity":0},
                                "opacity":"0",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "location":{
                                  "x":184,
                                  "y":646},
                                "size":{
                                  "width":95,
                                  "height":86},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0x797979}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"在 当前窗口 打开 满分学习的副本",
                                      "target":{
                                        "targetType":"page",
                                        "url":"满分学习的副本.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"86d2ec5bdf3e4df18326abce269b3e77",
                          "label":"免检",
                          "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0x333333,
                              "opacity":0},
                            "opacity":"0",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":389},
                            "size":{
                              "width":110,
                              "height":86},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0x797979}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"462d5a6ac2354efa9f213cfabe22cfb2",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"71aefb8876ab43eb8532d9dcf41d80a9",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0x333333,
                                  "opacity":0},
                                "opacity":"0",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "location":{
                                  "x":0,
                                  "y":389},
                                "size":{
                                  "width":110,
                                  "height":86},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0x797979}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"在 当前窗口 打开 六年免检办理及预约",
                                      "target":{
                                        "targetType":"page",
                                        "url":"六年免检办理及预约.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}]}]}]}]},
{
          "id":"8a73243730cc4620bc3b3070900ffeb9",
          "label":"顶部",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":49},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"434c07be34cc446ab427e9c89571a18e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":49},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/顶部_u43.png"}},
{
          "id":"65bb1381a4c546f7a2a3826c764769aa",
          "label":"底部",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":620},
            "size":{
              "width":375,
              "height":51},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e03e00ca9cf437f9935a8e3c7234ade",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":620},
                "size":{
                  "width":375,
                  "height":51},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/底部_u45.png"}},
{
          "id":"3772e426be7f4eb69207d6739de95e3a",
          "label":"机动车业务",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":120,
              "y":622},
            "size":{
              "width":124,
              "height":49},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b91d870b95674480b4a80634d7e7497e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":120,
                  "y":622},
                "size":{
                  "width":124,
                  "height":49},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 (动态面板) to 机动车业务 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["1cbc585bd7cc4cbeaaa74a8f77901729"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "compress":false}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 范围,<br>顶部,<br>底部,<br>机动车业务,<br>驾驶证业务",
                      "objectsToFades":[{
                          "objectPath":["795e6e78996842f0b5f36decd87220be"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8a73243730cc4620bc3b3070900ffeb9"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["65bb1381a4c546f7a2a3826c764769aa"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["3772e426be7f4eb69207d6739de95e3a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8f6e5f7ceb274483a20b2a0c3fe4a8a3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 (动态面板),<br>驾驶证业务,<br>e大厅1,<br>2,<br>1,<br>六年免检",
                      "objectsToFades":[{
                          "objectPath":["1cbc585bd7cc4cbeaaa74a8f77901729"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["9673da2b28004154aa19f6bf7e6dd083"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ac7e0d7f0ada45c383aa520d8749e486"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["5ea8f1b5a65e47d181308fb726a3b36e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d8d2c64aab924ce7ba7d7a125dddd6ab"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["09a636b505c442f38af0ff35e7c37a5b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f6e5f7ceb274483a20b2a0c3fe4a8a3",
          "label":"驾驶证业务",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":254,
              "y":622},
            "size":{
              "width":113,
              "height":49},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc0222e6954c474c94b6f5c444923ed2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":254,
                  "y":622},
                "size":{
                  "width":113,
                  "height":49},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 (动态面板) to 驾驶证业务 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["1cbc585bd7cc4cbeaaa74a8f77901729"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "compress":false}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 (动态面板),<br>机动车业务,<br>e大厅2,<br>8,<br>9",
                      "objectsToFades":[{
                          "objectPath":["1cbc585bd7cc4cbeaaa74a8f77901729"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["5241301c30cf497781cc62d3bd2dda05"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0080049e55fc43d38d5a3a7ea85df575"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f9dec202a5d94f85be48f3209778ce65"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["cad154f1db974af0ad7b43a9ca8a7a8e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 范围,<br>底部,<br>顶部,<br>机动车业务,<br>驾驶证业务",
                      "objectsToFades":[{
                          "objectPath":["795e6e78996842f0b5f36decd87220be"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["65bb1381a4c546f7a2a3826c764769aa"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8a73243730cc4620bc3b3070900ffeb9"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["3772e426be7f4eb69207d6739de95e3a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8f6e5f7ceb274483a20b2a0c3fe4a8a3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1cbc585bd7cc4cbeaaa74a8f77901729":{
      "scriptId":"u0"},
    "cad154f1db974af0ad7b43a9ca8a7a8e":{
      "scriptId":"u1"},
    "634ca19287c24f6dbfda306080ce6188":{
      "scriptId":"u2"},
    "f9dec202a5d94f85be48f3209778ce65":{
      "scriptId":"u3"},
    "dcb96dc7ff8b4af198211b502065af9c":{
      "scriptId":"u4"},
    "0080049e55fc43d38d5a3a7ea85df575":{
      "scriptId":"u5"},
    "0cb0c256e24c400a96f747477fa20287":{
      "scriptId":"u6"},
    "5241301c30cf497781cc62d3bd2dda05":{
      "scriptId":"u7"},
    "0540d783790942f0a6ddfbc990a66f75":{
      "scriptId":"u8"},
    "d8d2c64aab924ce7ba7d7a125dddd6ab":{
      "scriptId":"u9"},
    "b642cfdc3db34e27bc3dcbcc9c2969a9":{
      "scriptId":"u10"},
    "5ea8f1b5a65e47d181308fb726a3b36e":{
      "scriptId":"u11"},
    "502b2edcd8314cb4be4dde51ea36e0d8":{
      "scriptId":"u12"},
    "ac7e0d7f0ada45c383aa520d8749e486":{
      "scriptId":"u13"},
    "85b318446de3447d8051dd7137ee629a":{
      "scriptId":"u14"},
    "9673da2b28004154aa19f6bf7e6dd083":{
      "scriptId":"u15"},
    "a8223445bbb64420ab49dc48989886d8":{
      "scriptId":"u16"},
    "09a636b505c442f38af0ff35e7c37a5b":{
      "scriptId":"u17"},
    "dae74f26627f4b63a14523252eaefd1a":{
      "scriptId":"u18"},
    "795e6e78996842f0b5f36decd87220be":{
      "scriptId":"u19"},
    "71aefb8876ab43eb8532d9dcf41d80a9":{
      "scriptId":"u20"},
    "91f48be64cfc4ef28c5c244bb5d3dcf1":{
      "scriptId":"u21"},
    "b578a2d542ee4b3dbba81e9c913270e4":{
      "scriptId":"u22"},
    "fb82337bcae246419a588829ab8ab659":{
      "scriptId":"u23"},
    "a47b129951534194b21d626bdc412ef8":{
      "scriptId":"u24"},
    "d5002a76fa384f5da953050ec1c4a37d":{
      "scriptId":"u25"},
    "132cfbdcfc7b4ef097f97309c2452ce8":{
      "scriptId":"u26"},
    "7400bd1ab059488490db343e9df615c8":{
      "scriptId":"u27"},
    "0fddf80d42dd4aee8c0d1b1fc843e75f":{
      "scriptId":"u28"},
    "8ed436d7d1a14ec4833d584e0be56815":{
      "scriptId":"u29"},
    "6bac7e410a7e49a6965378e4b69449d2":{
      "scriptId":"u30"},
    "4086f42bcacd462a8e660ed8d4554abd":{
      "scriptId":"u31"},
    "c9014b202c5d476ca656a184d02ebe3b":{
      "scriptId":"u32"},
    "985d292f2982488280b8db42ec80fb01":{
      "scriptId":"u33"},
    "cb62bc8cd7ee41f7a1f3c2a6b3884759":{
      "scriptId":"u34"},
    "6d6200264d624a6dbf5fbec8651997e7":{
      "scriptId":"u35"},
    "d4bc710a1d6b4d97a5b228cdc6518c20":{
      "scriptId":"u36"},
    "045f2b07fae049809b8dda8d493b89fd":{
      "scriptId":"u37"},
    "6693e8fd211741e18b19409fad76edac":{
      "scriptId":"u38"},
    "0f306c6f816d42e0a94952eb67afd20e":{
      "scriptId":"u39"},
    "9e9a59d0c4614a2097a1352cb27e2a6e":{
      "scriptId":"u40"},
    "86d2ec5bdf3e4df18326abce269b3e77":{
      "scriptId":"u41"},
    "462d5a6ac2354efa9f213cfabe22cfb2":{
      "scriptId":"u42"},
    "8a73243730cc4620bc3b3070900ffeb9":{
      "scriptId":"u43"},
    "434c07be34cc446ab427e9c89571a18e":{
      "scriptId":"u44"},
    "65bb1381a4c546f7a2a3826c764769aa":{
      "scriptId":"u45"},
    "4e03e00ca9cf437f9935a8e3c7234ade":{
      "scriptId":"u46"},
    "3772e426be7f4eb69207d6739de95e3a":{
      "scriptId":"u47"},
    "b91d870b95674480b4a80634d7e7497e":{
      "scriptId":"u48"},
    "8f6e5f7ceb274483a20b2a0c3fe4a8a3":{
      "scriptId":"u49"},
    "dc0222e6954c474c94b6f5c444923ed2":{
      "scriptId":"u50"}}});