$axure.loadCurrentPage({
  "url":"举报资料.html",
  "generationDate":new Date(1503973156507.77),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"jvbao",
"yiche",
"mianfenquan"],
  "page":{
    "packageId":"e47b16a472424656b169366c0793eb6e",
    "type":"Axure:Page",
    "name":"举报资料",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b341fdfb581e49e78a1817568b176fe9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":647}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa5d452520f84c059a9a37ad93696c1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":647}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报资料/u0.png"}},
{
          "id":"b9f4669d0eae439e949eca0610616226",
          "label":"返回须知",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":90,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf67e6505de7449b9c31e3dc3eaba776",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":90,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If 值于 jvbao 等于 &quot;1&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetGlobalVariableValue",
                      "arguments":[{
                          "exprType":"globalVariableLiteral",
                          "variableName":"jvbao"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"1",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 违法举报须知",
                      "target":{
                        "targetType":"page",
                        "url":"违法举报须知.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 2<br> (Else If 值于 jvbao 等于 &quot;2&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetGlobalVariableValue",
                      "arguments":[{
                          "exprType":"globalVariableLiteral",
                          "variableName":"jvbao"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"2",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 历史举报",
                      "target":{
                        "targetType":"page",
                        "url":"历史举报.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85a8a5d3debb42beaf2f2061570dec58",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":12.5,
              "y":390},
            "size":{
              "width":350,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b57a9c8cfe5442282a839a2f7257343",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":12.5,
                  "y":390},
                "size":{
                  "width":350,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 确认按钮,<br>确认按钮,<br>(水平线),<br>蒙版",
                      "objectsToFades":[{
                          "objectPath":["d664a6d41b2c46b8b095b1f86c3248dc"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["4cd36538d8174d6289423d9f7b4d72ed"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["5131b109885e4d7ba9563a2e86fda774"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["174c96ee6ab7499ab5ce481b77e5d8e5"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed102b2a075a40a5828f898fe1e493a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":92},
            "size":{
              "width":30,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0a62af1056d478cad130780c4a35ec4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":92},
                "size":{
                  "width":30,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报资料/u6.png"}},
{
          "id":"174c96ee6ab7499ab5ce481b77e5d8e5",
          "label":"蒙版",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "opacity":"0.7",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "size":{
              "width":375,
              "height":647},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d727c445b7a401bb72299f59505d43b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "opacity":"0.7",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "size":{
                  "width":375,
                  "height":647},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报资料/蒙版_u8.png"}},
{
          "id":"d664a6d41b2c46b8b095b1f86c3248dc",
          "label":"确认按钮",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "verticalAlignment":"top",
            "lineSpacing":"28px",
            "paddingTop":"15",
            "location":{
              "x":35,
              "y":210},
            "size":{
              "width":306,
              "height":130},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE5E5E5},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4145e26dd2d14d49925ae0249acf9c37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "verticalAlignment":"top",
                "lineSpacing":"28px",
                "paddingTop":"15",
                "location":{
                  "x":35,
                  "y":210},
                "size":{
                  "width":306,
                  "height":130},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE5E5E5},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报资料/确认按钮_u10.png"}},
{
          "id":"4cd36538d8174d6289423d9f7b4d72ed",
          "label":"确认按钮",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4D9BDA,
              "opacity":1},
            "location":{
              "x":67,
              "y":295},
            "size":{
              "width":241,
              "height":35},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4ebd6d45ddd47e9b5798af6e6f997b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4D9BDA,
                  "opacity":1},
                "location":{
                  "x":67,
                  "y":295},
                "size":{
                  "width":241,
                  "height":35},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 举报成功详情",
                      "target":{
                        "targetType":"page",
                        "url":"举报成功详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/举报资料/确认按钮_u12.png"}},
{
          "id":"5131b109885e4d7ba9563a2e86fda774",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":false,
          "style":{
            "location":{
              "x":66.5000152587891,
              "y":285},
            "size":{
              "width":240,
              "height":10},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE5E5E5}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/举报资料/u14_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "b341fdfb581e49e78a1817568b176fe9":{
      "scriptId":"u0"},
    "fa5d452520f84c059a9a37ad93696c1c":{
      "scriptId":"u1"},
    "b9f4669d0eae439e949eca0610616226":{
      "scriptId":"u2"},
    "cf67e6505de7449b9c31e3dc3eaba776":{
      "scriptId":"u3"},
    "85a8a5d3debb42beaf2f2061570dec58":{
      "scriptId":"u4"},
    "4b57a9c8cfe5442282a839a2f7257343":{
      "scriptId":"u5"},
    "ed102b2a075a40a5828f898fe1e493a0":{
      "scriptId":"u6"},
    "b0a62af1056d478cad130780c4a35ec4":{
      "scriptId":"u7"},
    "174c96ee6ab7499ab5ce481b77e5d8e5":{
      "scriptId":"u8"},
    "1d727c445b7a401bb72299f59505d43b":{
      "scriptId":"u9"},
    "d664a6d41b2c46b8b095b1f86c3248dc":{
      "scriptId":"u10"},
    "4145e26dd2d14d49925ae0249acf9c37":{
      "scriptId":"u11"},
    "4cd36538d8174d6289423d9f7b4d72ed":{
      "scriptId":"u12"},
    "f4ebd6d45ddd47e9b5798af6e6f997b4":{
      "scriptId":"u13"},
    "5131b109885e4d7ba9563a2e86fda774":{
      "scriptId":"u14"}}});