$axure.loadCurrentPage({
  "url":"个人中心.html",
  "generationDate":new Date(1503973155426.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"jvbao",
"yiche",
"mianfenquan"],
  "page":{
    "packageId":"3b157f372a374ec5bbb8b211a37c92a6",
    "type":"Axure:Page",
    "name":"个人中心",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3d92fcbbc0cf44ff92c6f2eeb0f460f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":647}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"117d370b6f6a4f06a38ec6cdad404b96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":647}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心/u0.jpg"}},
{
          "id":"ba80e0b5610144e1ad53a362a245de8b",
          "label":"免检业务申请",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":-8,
              "y":320},
            "size":{
              "width":390,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b254c462b984701af4d757d661ee825",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":-8,
                  "y":320},
                "size":{
                  "width":390,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 值于 mianfenquan = &quot;1&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"mianfenquan"},
{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]}]}]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的免分券",
                      "target":{
                        "targetType":"page",
                        "url":"我的免分券.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e3de2a2e0a84ccab0f82f940f0263b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":90,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69d0002fa72844b29b01e01317544fcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":90,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2fca84760aab478dad952dc7b9d9fede",
          "label":"免检业务申请",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":-8,
              "y":280},
            "size":{
              "width":390,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed6988194014496c835aaa206ea82f01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":-8,
                  "y":280},
                "size":{
                  "width":390,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 值于 yiche = &quot;1&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"yiche"},
{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]}]}]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 自助移车",
                      "target":{
                        "targetType":"page",
                        "url":"自助移车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3d92fcbbc0cf44ff92c6f2eeb0f460f8":{
      "scriptId":"u0"},
    "117d370b6f6a4f06a38ec6cdad404b96":{
      "scriptId":"u1"},
    "ba80e0b5610144e1ad53a362a245de8b":{
      "scriptId":"u2"},
    "1b254c462b984701af4d757d661ee825":{
      "scriptId":"u3"},
    "4e3de2a2e0a84ccab0f82f940f0263b5":{
      "scriptId":"u4"},
    "69d0002fa72844b29b01e01317544fcf":{
      "scriptId":"u5"},
    "2fca84760aab478dad952dc7b9d9fede":{
      "scriptId":"u6"},
    "ed6988194014496c835aaa206ea82f01":{
      "scriptId":"u7"}}});