$axure.loadCurrentPage({
  "url":"人工服务.html",
  "generationDate":new Date(1503973156054.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"jvbao",
"yiche",
"mianfenquan"],
  "page":{
    "packageId":"226239bff6714924a05a751fde414158",
    "type":"Axure:Page",
    "name":"人工服务",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1aa2d517af72485cacab91d034aa717a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":647}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86086012d7524216b461ccae015083ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":647}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/人工服务/u0.png"}},
{
          "id":"77d2d73d1d034cad9c921415e9482359",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":20,
              "y":131},
            "size":{
              "width":340,
              "height":209},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cb3e142b78c455f8b27cf0ef5941f99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":20,
                  "y":131},
                "size":{
                  "width":340,
                  "height":209},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/人工服务/u2.png"}},
{
          "id":"affd71ca2c0943a39ed424034bfc3f52",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":136,
              "y":171},
            "size":{
              "width":239,
              "height":49},
            "visible":false,
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"320dc6f9800a47278d328db9620ead89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":136,
                  "y":171},
                "size":{
                  "width":239,
                  "height":49},
                "visible":false,
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/人工服务/u4.png"}},
{
          "id":"c483921e3291439caf63adda0e54ef91",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":250},
            "size":{
              "width":333,
              "height":120},
            "visible":false,
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e08f1cd3b69047e7bc6af6505e53db0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":0,
                  "y":250},
                "size":{
                  "width":333,
                  "height":120},
                "visible":false,
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/人工服务/u6.png"}},
{
          "id":"ac6007dda63f4fafafb6b59141c9a506",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":90,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8bba681ec154ef9a6ca49be61e0cc5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":90,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 机器人",
                      "target":{
                        "targetType":"page",
                        "url":"机器人.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e0ad17b25834cc78c1741a5afc6ad9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":597},
            "size":{
              "width":370,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7418d7fb97f740ddade26f86bc8f9e1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":597},
                "size":{
                  "width":370,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"连接成功",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (图片)",
                      "objectsToFades":[{
                          "objectPath":["787672fe76c54522a93953ac29e33a68"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"发送文字",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (图片),<br>(图片),<br>自助移车",
                      "objectsToFades":[{
                          "objectPath":["affd71ca2c0943a39ed424034bfc3f52"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["c483921e3291439caf63adda0e54ef91"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["90c4efbd6f224ef8b7d181de9fee52be"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"787672fe76c54522a93953ac29e33a68",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":14,
              "y":131},
            "size":{
              "width":351,
              "height":39},
            "visible":false,
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f8e287de48641208bfdcecfd2564608",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":14,
                  "y":131},
                "size":{
                  "width":351,
                  "height":39},
                "visible":false,
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/人工服务/u12.png"}},
{
          "id":"90c4efbd6f224ef8b7d181de9fee52be",
          "label":"自助移车",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":156.999984741211,
              "y":271},
            "size":{
              "width":83,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0ab961de9574b2db1d140f017ddf940",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":156.999984741211,
                  "y":271},
                "size":{
                  "width":83,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"返回在线",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 自助移车",
                      "target":{
                        "targetType":"page",
                        "url":"自助移车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1aa2d517af72485cacab91d034aa717a":{
      "scriptId":"u0"},
    "86086012d7524216b461ccae015083ad":{
      "scriptId":"u1"},
    "77d2d73d1d034cad9c921415e9482359":{
      "scriptId":"u2"},
    "2cb3e142b78c455f8b27cf0ef5941f99":{
      "scriptId":"u3"},
    "affd71ca2c0943a39ed424034bfc3f52":{
      "scriptId":"u4"},
    "320dc6f9800a47278d328db9620ead89":{
      "scriptId":"u5"},
    "c483921e3291439caf63adda0e54ef91":{
      "scriptId":"u6"},
    "e08f1cd3b69047e7bc6af6505e53db0f":{
      "scriptId":"u7"},
    "ac6007dda63f4fafafb6b59141c9a506":{
      "scriptId":"u8"},
    "b8bba681ec154ef9a6ca49be61e0cc5a":{
      "scriptId":"u9"},
    "7e0ad17b25834cc78c1741a5afc6ad9a":{
      "scriptId":"u10"},
    "7418d7fb97f740ddade26f86bc8f9e1d":{
      "scriptId":"u11"},
    "787672fe76c54522a93953ac29e33a68":{
      "scriptId":"u12"},
    "4f8e287de48641208bfdcecfd2564608":{
      "scriptId":"u13"},
    "90c4efbd6f224ef8b7d181de9fee52be":{
      "scriptId":"u14"},
    "f0ab961de9574b2db1d140f017ddf940":{
      "scriptId":"u15"}}});