$axure.loadCurrentPage({
  "url":"历史成绩.html",
  "generationDate":new Date(1503998488514.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"jvbao",
"yiche",
"mianfenquan"],
  "page":{
    "packageId":"85ede963ac244f4990f91ae7eb4b025a",
    "type":"Axure:Page",
    "name":"历史成绩",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8bcc3b7077584448bac8240bb8d8a09e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":647},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"602846ab594b405b81e83443db7fdab2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":647},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史成绩/u0.png"}},
{
          "id":"c63c3fee89864720acb710791f2b1715",
          "label":"模拟考试1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":100,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aec60563084e4b3c90017b0409116d2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":100,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"返回在线",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 驾考在线学习",
                      "target":{
                        "targetType":"page",
                        "url":"驾考在线学习.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47789413a9e045c29b522d62fa34643e",
          "label":"模拟考试1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":310},
            "size":{
              "width":380,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9a3706a292e4fe684857679b0b0a397",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":310},
                "size":{
                  "width":380,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"返回在线",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的错题",
                      "target":{
                        "targetType":"page",
                        "url":"我的错题.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8806e91fc3a046948f663a97c5386a40",
          "label":"模拟考试1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":400},
            "size":{
              "width":380,
              "height":250},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b3fd8a3bd0e4340a61e44fa398e75fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":400},
                "size":{
                  "width":380,
                  "height":250},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"返回在线",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看试卷",
                      "target":{
                        "targetType":"page",
                        "url":"查看试卷.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12dc06eb8f3d42998ca3b080e00597a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微軟正黑體 Bold', '微軟正黑體'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":154,
              "y":416},
            "size":{
              "width":40,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8caae48fbb2141e3a008efe63ea19bc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微軟正黑體 Bold', '微軟正黑體'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":416},
                "size":{
                  "width":40,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e040f4ad28e64a6cb9e87255b6ffc60c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微軟正黑體 Bold', '微軟正黑體'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":154,
              "y":465},
            "size":{
              "width":40,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a20f877d4fb483ea407215554606cde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微軟正黑體 Bold', '微軟正黑體'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":465},
                "size":{
                  "width":40,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e30a5b7da9c4e6f9536c33636538f5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微軟正黑體 Bold', '微軟正黑體'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":154,
              "y":516},
            "size":{
              "width":40,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d49abad75cc84c96a5f7d7794564ec61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微軟正黑體 Bold', '微軟正黑體'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":516},
                "size":{
                  "width":40,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a520d1bce2a4f23aa2d1cde429384be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微軟正黑體 Bold', '微軟正黑體'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":154,
              "y":565},
            "size":{
              "width":40,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"101173649ace40fdba7b559c8665e053",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微軟正黑體 Bold', '微軟正黑體'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":565},
                "size":{
                  "width":40,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0213df162b943a18b3e535a05eca5d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微軟正黑體 Bold', '微軟正黑體'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":154,
              "y":615},
            "size":{
              "width":40,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"088d24cbca7347699b2a1ff3aa52f561",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微軟正黑體 Bold', '微軟正黑體'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":615},
                "size":{
                  "width":40,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8bcc3b7077584448bac8240bb8d8a09e":{
      "scriptId":"u0"},
    "602846ab594b405b81e83443db7fdab2":{
      "scriptId":"u1"},
    "c63c3fee89864720acb710791f2b1715":{
      "scriptId":"u2"},
    "aec60563084e4b3c90017b0409116d2f":{
      "scriptId":"u3"},
    "47789413a9e045c29b522d62fa34643e":{
      "scriptId":"u4"},
    "a9a3706a292e4fe684857679b0b0a397":{
      "scriptId":"u5"},
    "8806e91fc3a046948f663a97c5386a40":{
      "scriptId":"u6"},
    "7b3fd8a3bd0e4340a61e44fa398e75fe":{
      "scriptId":"u7"},
    "12dc06eb8f3d42998ca3b080e00597a8":{
      "scriptId":"u8"},
    "8caae48fbb2141e3a008efe63ea19bc1":{
      "scriptId":"u9"},
    "e040f4ad28e64a6cb9e87255b6ffc60c":{
      "scriptId":"u10"},
    "6a20f877d4fb483ea407215554606cde":{
      "scriptId":"u11"},
    "5e30a5b7da9c4e6f9536c33636538f5c":{
      "scriptId":"u12"},
    "d49abad75cc84c96a5f7d7794564ec61":{
      "scriptId":"u13"},
    "7a520d1bce2a4f23aa2d1cde429384be":{
      "scriptId":"u14"},
    "101173649ace40fdba7b559c8665e053":{
      "scriptId":"u15"},
    "e0213df162b943a18b3e535a05eca5d6":{
      "scriptId":"u16"},
    "088d24cbca7347699b2a1ff3aa52f561":{
      "scriptId":"u17"}}});