$axure.loadCurrentPage({
  "url":"预约考试时间.html",
  "generationDate":new Date(1503998489682.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"jvbao",
"yiche",
"mianfenquan"],
  "page":{
    "packageId":"1efebd618ca147868ad9e38dd2963e95",
    "type":"Axure:Page",
    "name":"预约考试时间",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ab394a1e0e4a4ec493e913e89d3a564d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":647}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05773259089249c1bd40734e2bb5be56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":647}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约考试时间/u0.png"}},
{
          "id":"b098195a91bd48bcbc70a7ea0a21288f",
          "label":"模拟考试1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":10,
              "y":400},
            "size":{
              "width":350,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40bebd22fad444c78f6ddecdd644928c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":10,
                  "y":400},
                "size":{
                  "width":350,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 蒙版,<br>确认按钮,<br>确认按钮,<br>(水平线)",
                      "objectsToFades":[{
                          "objectPath":["ca8d8126ae954ef6b0f9cb8312bbea70"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f37ce8e95b434d68825d40c5a01f5e37"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2a453618fe794cc9bf003034281ad9dc"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6964845d5fe14a4e8f64bd0fa116fcb1"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 (图片),<br>模拟考试1",
                      "objectsToFades":[{
                          "objectPath":["ab394a1e0e4a4ec493e913e89d3a564d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b098195a91bd48bcbc70a7ea0a21288f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca8d8126ae954ef6b0f9cb8312bbea70",
          "label":"蒙版",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "opacity":"0.7",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "size":{
              "width":375,
              "height":647},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c398b6ab8564e50b201b9945dd06948",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "opacity":"0.7",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "size":{
                  "width":375,
                  "height":647},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报资料/蒙版_u8.png"}},
{
          "id":"f37ce8e95b434d68825d40c5a01f5e37",
          "label":"确认按钮",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "verticalAlignment":"top",
            "lineSpacing":"28px",
            "paddingTop":"25",
            "location":{
              "x":35,
              "y":210},
            "size":{
              "width":306,
              "height":130},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE5E5E5},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de6d0c1f9e204346b5b3b351f8e273a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "verticalAlignment":"top",
                "lineSpacing":"28px",
                "paddingTop":"25",
                "location":{
                  "x":35,
                  "y":210},
                "size":{
                  "width":306,
                  "height":130},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE5E5E5},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/举报资料/确认按钮_u10.png"}},
{
          "id":"2a453618fe794cc9bf003034281ad9dc",
          "label":"确认按钮",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4D9BDA,
              "opacity":1},
            "location":{
              "x":67,
              "y":295},
            "size":{
              "width":241,
              "height":35},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b69c60c234de4906824ebdd938f22407",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4D9BDA,
                  "opacity":1},
                "location":{
                  "x":67,
                  "y":295},
                "size":{
                  "width":241,
                  "height":35},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 学习记录",
                      "target":{
                        "targetType":"page",
                        "url":"学习记录_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/举报资料/确认按钮_u12.png"}},
{
          "id":"6964845d5fe14a4e8f64bd0fa116fcb1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":false,
          "style":{
            "location":{
              "x":67,
              "y":285},
            "size":{
              "width":240,
              "height":10},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE5E5E5}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/举报资料/u14_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ab394a1e0e4a4ec493e913e89d3a564d":{
      "scriptId":"u0"},
    "05773259089249c1bd40734e2bb5be56":{
      "scriptId":"u1"},
    "b098195a91bd48bcbc70a7ea0a21288f":{
      "scriptId":"u2"},
    "40bebd22fad444c78f6ddecdd644928c":{
      "scriptId":"u3"},
    "ca8d8126ae954ef6b0f9cb8312bbea70":{
      "scriptId":"u4"},
    "0c398b6ab8564e50b201b9945dd06948":{
      "scriptId":"u5"},
    "f37ce8e95b434d68825d40c5a01f5e37":{
      "scriptId":"u6"},
    "de6d0c1f9e204346b5b3b351f8e273a3":{
      "scriptId":"u7"},
    "2a453618fe794cc9bf003034281ad9dc":{
      "scriptId":"u8"},
    "b69c60c234de4906824ebdd938f22407":{
      "scriptId":"u9"},
    "6964845d5fe14a4e8f64bd0fa116fcb1":{
      "scriptId":"u10"}}});