$axure.loadCurrentPage({
  "url":"审验学习须知.html",
  "generationDate":new Date(1503998488691.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"jvbao",
"yiche",
"mianfenquan"],
  "page":{
    "packageId":"059f3e79fdba4093bde5531051089049",
    "type":"Axure:Page",
    "name":"审验学习须知",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c80eb78f08e64b508a523f625294cca5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":647}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e0de0105f334ccfbc6ab788df5157c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":647}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/审验学习须知/u0.png"}},
{
          "id":"c7a11931ad6e4c468c2a58e7246f9d93",
          "label":"模拟考试1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":10,
              "y":396},
            "size":{
              "width":360,
              "height":64},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dab4b79f3c145adb519efda99629f65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":10,
                  "y":396},
                "size":{
                  "width":360,
                  "height":64},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 学习视频",
                      "target":{
                        "targetType":"page",
                        "url":"学习视频.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c0f88c84e13492cb21ad63eac8f1b2a",
          "label":"模拟考试1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":130,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87d5aa3aa01d4bb7ade146ea8141dc33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":130,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 审验学习",
                      "target":{
                        "targetType":"page",
                        "url":"审验学习.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17a4e34475b9461c91210667be9c6f11",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":370},
            "size":{
              "width":253,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"028d245e3ca144deba5940c5a9539617",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":370},
                "size":{
                  "width":253,
                  "height":16}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "c80eb78f08e64b508a523f625294cca5":{
      "scriptId":"u0"},
    "7e0de0105f334ccfbc6ab788df5157c2":{
      "scriptId":"u1"},
    "c7a11931ad6e4c468c2a58e7246f9d93":{
      "scriptId":"u2"},
    "2dab4b79f3c145adb519efda99629f65":{
      "scriptId":"u3"},
    "9c0f88c84e13492cb21ad63eac8f1b2a":{
      "scriptId":"u4"},
    "87d5aa3aa01d4bb7ade146ea8141dc33":{
      "scriptId":"u5"},
    "17a4e34475b9461c91210667be9c6f11":{
      "scriptId":"u6"},
    "028d245e3ca144deba5940c5a9539617":{
      "scriptId":"u7"}}});