$axure.loadCurrentPage({
  "url":"机器人-联想.html",
  "generationDate":new Date(1503998486755.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"jvbao",
"yiche",
"mianfenquan"],
  "page":{
    "packageId":"5cad4d07c9ab493185640fa9aedcf460",
    "type":"Axure:Page",
    "name":"机器人-联想",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9263fe40830a442586bf51af0186e8ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":647}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cc98d2cd0e34fa29e95395741aa69ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":647}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机器人-联想/u0.png"}},
{
          "id":"763883f6269949f7aa35563a0605f2a5",
          "label":"遮挡",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":0,
              "y":96},
            "size":{
              "width":380,
              "height":286},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"132b059df9eb453589043758672a41f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":0,
                  "y":96},
                "size":{
                  "width":380,
                  "height":286},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机器人-联想/遮挡_u2.png"}},
{
          "id":"cfb69f4943a84cd28b9a57ee27a4b547",
          "label":"问",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":192,
              "y":96},
            "size":{
              "width":188,
              "height":59},
            "visible":false,
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16e92926d99f41aeb0a90a369afdb439",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":192,
                  "y":96},
                "size":{
                  "width":188,
                  "height":59},
                "visible":false,
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机器人-联想/问_u4.png"}},
{
          "id":"3ba7d9e53d264d099399b993e69cf709",
          "label":"答",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":165},
            "size":{
              "width":321,
              "height":117},
            "visible":false,
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88db1886aebd4b19b23529f33aca58ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":0,
                  "y":165},
                "size":{
                  "width":321,
                  "height":117},
                "visible":false,
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机器人-联想/答_u6.png"}},
{
          "id":"60e8bcebea9743b4b76cad6157e34749",
          "label":"联想",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":3,
              "y":281},
            "size":{
              "width":373,
              "height":101},
            "visible":false,
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07d923751d384199a9f7c6daada1617a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":3,
                  "y":281},
                "size":{
                  "width":373,
                  "height":101},
                "visible":false,
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 问,<br>答",
                      "objectsToFades":[{
                          "objectPath":["cfb69f4943a84cd28b9a57ee27a4b547"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["3ba7d9e53d264d099399b993e69cf709"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/机器人-联想/联想_u8.png"}},
{
          "id":"5cfd0bba413a4251b30d141afd5b3c1b",
          "label":"输入框",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":387},
            "size":{
              "width":279,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7180efd75bc34a6b88344710cb271b81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":387},
                "size":{
                  "width":279,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 我年审,<br>联想",
                      "objectsToFades":[{
                          "objectPath":["7b8c89f9a2fc4e8c9d63b9210009b2a1"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["60e8bcebea9743b4b76cad6157e34749"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/机器人-联想/输入框_u10.png"}},
{
          "id":"7b8c89f9a2fc4e8c9d63b9210009b2a1",
          "label":"我年审",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":47,
              "y":396},
            "size":{
              "width":263,
              "height":20},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d4851c6c4c44455ade6f50be9fd914b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":47,
                  "y":396},
                "size":{
                  "width":263,
                  "height":20},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机器人-联想/我年审_u12.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9263fe40830a442586bf51af0186e8ef":{
      "scriptId":"u0"},
    "7cc98d2cd0e34fa29e95395741aa69ed":{
      "scriptId":"u1"},
    "763883f6269949f7aa35563a0605f2a5":{
      "scriptId":"u2"},
    "132b059df9eb453589043758672a41f6":{
      "scriptId":"u3"},
    "cfb69f4943a84cd28b9a57ee27a4b547":{
      "scriptId":"u4"},
    "16e92926d99f41aeb0a90a369afdb439":{
      "scriptId":"u5"},
    "3ba7d9e53d264d099399b993e69cf709":{
      "scriptId":"u6"},
    "88db1886aebd4b19b23529f33aca58ab":{
      "scriptId":"u7"},
    "60e8bcebea9743b4b76cad6157e34749":{
      "scriptId":"u8"},
    "07d923751d384199a9f7c6daada1617a":{
      "scriptId":"u9"},
    "5cfd0bba413a4251b30d141afd5b3c1b":{
      "scriptId":"u10"},
    "7180efd75bc34a6b88344710cb271b81":{
      "scriptId":"u11"},
    "7b8c89f9a2fc4e8c9d63b9210009b2a1":{
      "scriptId":"u12"},
    "1d4851c6c4c44455ade6f50be9fd914b":{
      "scriptId":"u13"}}});