$axure.loadCurrentPage({
  "url":"机器人.html",
  "generationDate":new Date(1503998486540.19),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"jvbao",
"yiche",
"mianfenquan"],
  "page":{
    "packageId":"b979b6a7c5a14bb2b2c30b19f64aed9e",
    "type":"Axure:Page",
    "name":"机器人",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"aac7750f04a44381aef4eb9b65677e25",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":647}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e4d9f2a4f9840a9ac8903d9f8f995c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":647}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机器人/u0.jpg"}},
{
          "id":"0a8a9472cd53422686de93051aaf0199",
          "label":"模拟考试1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":110,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5463f58a3e945f9904808dfded2d165",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":110,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"返回在线",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a820f30dc02481bb5a4bc350b7c82dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":44,
              "y":121},
            "size":{
              "width":246,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"374e6d65c8f14a25b94a4f9ee876f1a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":44,
                  "y":121},
                "size":{
                  "width":246,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机器人/u4.png"}},
{
          "id":"cd46c8c5c2d242f2a1d5b4e9ab85eb00",
          "label":"人工服务",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":44,
              "y":151},
            "size":{
              "width":176,
              "height":39},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5741e18c31674c0f89480cce2eb9a440",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":44,
                  "y":151},
                "size":{
                  "width":176,
                  "height":39},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"返回在线",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 人工服务",
                      "target":{
                        "targetType":"page",
                        "url":"人工服务.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61df57c24484445585202a847fb1cbe2",
          "label":"遮挡",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":-10,
              "y":201},
            "size":{
              "width":380,
              "height":399},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b23fc97d35548aca4db0441a2098a5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":-10,
                  "y":201},
                "size":{
                  "width":380,
                  "height":399},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机器人/遮挡_u8.png"}},
{
          "id":"448a19f01fcb4fda83ae0c13c2a1fa36",
          "label":"字",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":19,
              "y":206},
            "size":{
              "width":351,
              "height":178},
            "visible":false,
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d18e96b6a53f4560acaf68e3e0c77da2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":19,
                  "y":206},
                "size":{
                  "width":351,
                  "height":178},
                "visible":false,
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机器人/字_u10.png"}},
{
          "id":"83db7d3dc91e44ebaa22fe762eb10f2b",
          "label":"图",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":380},
            "size":{
              "width":351,
              "height":213},
            "visible":false,
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fdea874671a45b0a6dc744765431643",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":0,
                  "y":380},
                "size":{
                  "width":351,
                  "height":213},
                "visible":false,
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机器人/图_u12.png"}},
{
          "id":"b1b0fe8ef15b4d889fc3857ff4ff50e1",
          "label":"违法举报",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":30,
              "y":504},
            "size":{
              "width":116,
              "height":24},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8040b4f0cfc24a20bbe24729eb98d319",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":30,
                  "y":504},
                "size":{
                  "width":116,
                  "height":24},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"返回在线",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 违法举报须知",
                      "target":{
                        "targetType":"page",
                        "url":"违法举报须知.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad56c4fa6a6c4fdaa025f57d23399569",
          "label":"自助移车",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":30,
              "y":528},
            "size":{
              "width":116,
              "height":24},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e88bf0986ee4fd4a0afa84e05213c55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":30,
                  "y":528},
                "size":{
                  "width":116,
                  "height":24},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"返回在线",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 自助移车",
                      "target":{
                        "targetType":"page",
                        "url":"自助移车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5051ca98b6d34e7caf41467348210693",
          "label":"网上评价",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":30,
              "y":552},
            "size":{
              "width":116,
              "height":24},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a356ebe3c014e82ad0c81aedc5d0a50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":30,
                  "y":552},
                "size":{
                  "width":116,
                  "height":24},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"返回在线",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 网上评价",
                      "target":{
                        "targetType":"page",
                        "url":"网上评价.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ee2bd36fc5b48d492fb34334d1a30bf",
          "label":"模拟考试1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":603},
            "size":{
              "width":370,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9419e6a1c8b4658bf12d883f1c96cf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":603},
                "size":{
                  "width":370,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"字",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 字",
                      "objectsToFades":[{
                          "objectPath":["448a19f01fcb4fda83ae0c13c2a1fa36"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"图",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 图,<br>网上评价,<br>自助移车,<br>违法举报",
                      "objectsToFades":[{
                          "objectPath":["83db7d3dc91e44ebaa22fe762eb10f2b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["5051ca98b6d34e7caf41467348210693"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ad56c4fa6a6c4fdaa025f57d23399569"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b1b0fe8ef15b4d889fc3857ff4ff50e1"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "aac7750f04a44381aef4eb9b65677e25":{
      "scriptId":"u0"},
    "2e4d9f2a4f9840a9ac8903d9f8f995c9":{
      "scriptId":"u1"},
    "0a8a9472cd53422686de93051aaf0199":{
      "scriptId":"u2"},
    "c5463f58a3e945f9904808dfded2d165":{
      "scriptId":"u3"},
    "8a820f30dc02481bb5a4bc350b7c82dc":{
      "scriptId":"u4"},
    "374e6d65c8f14a25b94a4f9ee876f1a5":{
      "scriptId":"u5"},
    "cd46c8c5c2d242f2a1d5b4e9ab85eb00":{
      "scriptId":"u6"},
    "5741e18c31674c0f89480cce2eb9a440":{
      "scriptId":"u7"},
    "61df57c24484445585202a847fb1cbe2":{
      "scriptId":"u8"},
    "6b23fc97d35548aca4db0441a2098a5d":{
      "scriptId":"u9"},
    "448a19f01fcb4fda83ae0c13c2a1fa36":{
      "scriptId":"u10"},
    "d18e96b6a53f4560acaf68e3e0c77da2":{
      "scriptId":"u11"},
    "83db7d3dc91e44ebaa22fe762eb10f2b":{
      "scriptId":"u12"},
    "9fdea874671a45b0a6dc744765431643":{
      "scriptId":"u13"},
    "b1b0fe8ef15b4d889fc3857ff4ff50e1":{
      "scriptId":"u14"},
    "8040b4f0cfc24a20bbe24729eb98d319":{
      "scriptId":"u15"},
    "ad56c4fa6a6c4fdaa025f57d23399569":{
      "scriptId":"u16"},
    "6e88bf0986ee4fd4a0afa84e05213c55":{
      "scriptId":"u17"},
    "5051ca98b6d34e7caf41467348210693":{
      "scriptId":"u18"},
    "0a356ebe3c014e82ad0c81aedc5d0a50":{
      "scriptId":"u19"},
    "4ee2bd36fc5b48d492fb34334d1a30bf":{
      "scriptId":"u20"},
    "f9419e6a1c8b4658bf12d883f1c96cf5":{
      "scriptId":"u21"}}});