$axure.loadCurrentPage({
  "url":"办事大厅叫号查询.html",
  "generationDate":new Date(1503998488119.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"jvbao",
"yiche",
"mianfenquan"],
  "page":{
    "packageId":"801c33668f6347ecbdd4483be49d55f7",
    "type":"Axure:Page",
    "name":"办事大厅叫号查询",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"efd7f494834b4b159ee83e22c4a28919",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":647}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"634484e4e6204f5cb3c511e8521f9c78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":647}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/办事大厅叫号查询/u0.png"}},
{
          "id":"d89363a3170049a084c8d268f4f5489d",
          "label":"返回首页1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":90,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0fa04f36029420b9562c91be98f18df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":90,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7efe3e138a314759bfa2f1494fb763f2",
          "label":"选所",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":370,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f720a3caeccf4a07be32f07ca5b40a62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":370,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 分所",
                      "objectsToFades":[{
                          "objectPath":["c4976b0ec8ff46e090f73efcf8af05bc"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4976b0ec8ff46e090f73efcf8af05bc",
          "label":"分所",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":90},
            "size":{
              "width":375,
              "height":378},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"311a2a450ede4c209b9880ec06456d4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":375,
                  "height":378},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 选了所,<br>返回首页2,<br>选业务",
                      "objectsToFades":[{
                          "objectPath":["77a11d1bdc3244bb967dd8a3dd5608fa"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["5dc801f4550f40368cffe01f9c99540a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f155d69dc24844c1af3fed383b7e5b17"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 (图片),<br>返回首页1,<br>分所",
                      "objectsToFades":[{
                          "objectPath":["efd7f494834b4b159ee83e22c4a28919"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d89363a3170049a084c8d268f4f5489d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["c4976b0ec8ff46e090f73efcf8af05bc"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/办事大厅叫号查询/分所_u6.png"}},
{
          "id":"77a11d1bdc3244bb967dd8a3dd5608fa",
          "label":"选了所",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "size":{
              "width":375,
              "height":647},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4f178aa5140464fadc3cf8b398eecd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "size":{
                  "width":375,
                  "height":647},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/办事大厅叫号查询/选了所_u8.png"}},
{
          "id":"5dc801f4550f40368cffe01f9c99540a",
          "label":"返回首页2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":90,
              "height":40},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbd14641751245c7bd6a1033db92a0a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":90,
                  "height":40},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f155d69dc24844c1af3fed383b7e5b17",
          "label":"选业务",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":90},
            "size":{
              "width":370,
              "height":50},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"353223e593d046ffa0093bdb2ead6179",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":370,
                  "height":50},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 业务",
                      "objectsToFades":[{
                          "objectPath":["ada9112835d7444fa95534c67e6371b1"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ada9112835d7444fa95534c67e6371b1",
          "label":"业务",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":140},
            "size":{
              "width":375,
              "height":236},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"572b20e996e749c0a0af7bd436cb5b38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":0,
                  "y":140},
                "size":{
                  "width":375,
                  "height":236},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 返回首页3,<br>选了所和业务",
                      "objectsToFades":[{
                          "objectPath":["eb407b07a80b4188a051863003bdef1c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["dcf042b50a244cb191ed0fcf2bd29ae0"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/办事大厅叫号查询/业务_u14.png"}},
{
          "id":"dcf042b50a244cb191ed0fcf2bd29ae0",
          "label":"选了所和业务",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "size":{
              "width":375,
              "height":647},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c07a71af0abc49cf82679ee7279481ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "size":{
                  "width":375,
                  "height":647},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/办事大厅叫号查询/选了所和业务_u16.png"}},
{
          "id":"eb407b07a80b4188a051863003bdef1c",
          "label":"返回首页3",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":90,
              "height":40},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f387208629a54917a145600197e56e4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":90,
                  "height":40},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "efd7f494834b4b159ee83e22c4a28919":{
      "scriptId":"u0"},
    "634484e4e6204f5cb3c511e8521f9c78":{
      "scriptId":"u1"},
    "d89363a3170049a084c8d268f4f5489d":{
      "scriptId":"u2"},
    "d0fa04f36029420b9562c91be98f18df":{
      "scriptId":"u3"},
    "7efe3e138a314759bfa2f1494fb763f2":{
      "scriptId":"u4"},
    "f720a3caeccf4a07be32f07ca5b40a62":{
      "scriptId":"u5"},
    "c4976b0ec8ff46e090f73efcf8af05bc":{
      "scriptId":"u6"},
    "311a2a450ede4c209b9880ec06456d4b":{
      "scriptId":"u7"},
    "77a11d1bdc3244bb967dd8a3dd5608fa":{
      "scriptId":"u8"},
    "f4f178aa5140464fadc3cf8b398eecd4":{
      "scriptId":"u9"},
    "5dc801f4550f40368cffe01f9c99540a":{
      "scriptId":"u10"},
    "bbd14641751245c7bd6a1033db92a0a6":{
      "scriptId":"u11"},
    "f155d69dc24844c1af3fed383b7e5b17":{
      "scriptId":"u12"},
    "353223e593d046ffa0093bdb2ead6179":{
      "scriptId":"u13"},
    "ada9112835d7444fa95534c67e6371b1":{
      "scriptId":"u14"},
    "572b20e996e749c0a0af7bd436cb5b38":{
      "scriptId":"u15"},
    "dcf042b50a244cb191ed0fcf2bd29ae0":{
      "scriptId":"u16"},
    "c07a71af0abc49cf82679ee7279481ee":{
      "scriptId":"u17"},
    "eb407b07a80b4188a051863003bdef1c":{
      "scriptId":"u18"},
    "f387208629a54917a145600197e56e4d":{
      "scriptId":"u19"}}});