$axure.loadCurrentPage({
  "url":"网上评价.html",
  "generationDate":new Date(1503973162210.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"jvbao",
"yiche",
"mianfenquan"],
  "page":{
    "packageId":"23bc7fd2cae649e3bc962d6b3b401a12",
    "type":"Axure:Page",
    "name":"网上评价",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"69b8a9d29e1e49089dc94302db9862e5",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":377,
              "height":650}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"19c6b3699fd24db5b5148c18fd57ad27",
              "label":"已评价",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a46b6d040e9143fc9c654dd248f96f15",
                  "label":"",
                  "parentDynamicPanel":"69b8a9d29e1e49089dc94302db9862e5",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":647}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8a9857bfda41405786e8090c6d48d7d9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"69b8a9d29e1e49089dc94302db9862e5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":375,
                          "height":647}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/网上评价/u1.jpg"}},
{
                  "id":"5c96e78a0c344d119c7ff9555d9453eb",
                  "label":"",
                  "parentDynamicPanel":"69b8a9d29e1e49089dc94302db9862e5",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":95,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1e2d4acc13e94871812c46eef1d11516",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"69b8a9d29e1e49089dc94302db9862e5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":95,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"26ae79eb1eb94c32b20e13df3c1f1852",
                  "label":"待评价",
                  "parentDynamicPanel":"69b8a9d29e1e49089dc94302db9862e5",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":175,
                      "y":40},
                    "size":{
                      "width":200,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f2c17a367b744d0d8e1e90d5e9439df2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"69b8a9d29e1e49089dc94302db9862e5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":175,
                          "y":40},
                        "size":{
                          "width":200,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 待评价",
                              "panelsToStates":[{
                                  "panelPath":["69b8a9d29e1e49089dc94302db9862e5"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"57e3e2bd9b71486c8a5012ee381ac411",
              "label":"待评价",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"31c9edf876414bc08ed1fda3b9e497ee",
                  "label":"",
                  "parentDynamicPanel":"69b8a9d29e1e49089dc94302db9862e5",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":647}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c4f167cfb5c149f0a40e2c051a8ff18f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"69b8a9d29e1e49089dc94302db9862e5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":375,
                          "height":647}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/网上评价/u7.png"}},
{
                  "id":"dcc678e576d94ebebf7dff99b96e8e0d",
                  "label":"免检业务申请",
                  "parentDynamicPanel":"69b8a9d29e1e49089dc94302db9862e5",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":110},
                    "size":{
                      "width":390,
                      "height":130},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bdf3c903279a46379e0d85a0b0610885",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"69b8a9d29e1e49089dc94302db9862e5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":110},
                        "size":{
                          "width":390,
                          "height":130},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 网上评价填写",
                              "target":{
                                "targetType":"page",
                                "url":"网上评价填写.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8572a1fc596f45a3a78efd491f6cf4c2",
                  "label":"",
                  "parentDynamicPanel":"69b8a9d29e1e49089dc94302db9862e5",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":90,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"021b0058d05a43139fce2ba6a8cdfc8d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"69b8a9d29e1e49089dc94302db9862e5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":90,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2241cafc49024139bf260730e9d9d02e",
                  "label":"免检业务申请",
                  "parentDynamicPanel":"69b8a9d29e1e49089dc94302db9862e5",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":50},
                    "size":{
                      "width":190,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"885a527098d84b78964ba9fb73d19288",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"69b8a9d29e1e49089dc94302db9862e5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":50},
                        "size":{
                          "width":190,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 已评价",
                              "panelsToStates":[{
                                  "panelPath":["69b8a9d29e1e49089dc94302db9862e5"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "69b8a9d29e1e49089dc94302db9862e5":{
      "scriptId":"u0"},
    "a46b6d040e9143fc9c654dd248f96f15":{
      "scriptId":"u1"},
    "8a9857bfda41405786e8090c6d48d7d9":{
      "scriptId":"u2"},
    "5c96e78a0c344d119c7ff9555d9453eb":{
      "scriptId":"u3"},
    "1e2d4acc13e94871812c46eef1d11516":{
      "scriptId":"u4"},
    "26ae79eb1eb94c32b20e13df3c1f1852":{
      "scriptId":"u5"},
    "f2c17a367b744d0d8e1e90d5e9439df2":{
      "scriptId":"u6"},
    "31c9edf876414bc08ed1fda3b9e497ee":{
      "scriptId":"u7"},
    "c4f167cfb5c149f0a40e2c051a8ff18f":{
      "scriptId":"u8"},
    "dcc678e576d94ebebf7dff99b96e8e0d":{
      "scriptId":"u9"},
    "bdf3c903279a46379e0d85a0b0610885":{
      "scriptId":"u10"},
    "8572a1fc596f45a3a78efd491f6cf4c2":{
      "scriptId":"u11"},
    "021b0058d05a43139fce2ba6a8cdfc8d":{
      "scriptId":"u12"},
    "2241cafc49024139bf260730e9d9d02e":{
      "scriptId":"u13"},
    "885a527098d84b78964ba9fb73d19288":{
      "scriptId":"u14"}}});