$axure.loadCurrentPage({
  "url":"考试成绩.html",
  "generationDate":new Date(1503973158147.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"jvbao",
"yiche",
"mianfenquan"],
  "page":{
    "packageId":"beec774a6b674d2aa01a023e601479e2",
    "type":"Axure:Page",
    "name":"考试成绩",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"366f87c55af64ab18a151fefac675905",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":647}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e20316f4cfd4189826e9b34708fe669",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":647}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考试成绩/u0.png"}},
{
          "id":"f6d4a4dd8feb41b688afb9c73e5d8ad2",
          "label":"模拟考试1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":100,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35e28676e7cb483aa56535d803ff374e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":100,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"返回在线",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 驾考在线学习",
                      "target":{
                        "targetType":"page",
                        "url":"驾考在线学习.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"881a57147c924648afdbe4adb1a2d313",
          "label":"模拟考试1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":360},
            "size":{
              "width":380,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b7afd3e248c4526ad15e42268596664",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":360},
                "size":{
                  "width":380,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"返回在线",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的错题",
                      "target":{
                        "targetType":"page",
                        "url":"我的错题.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc7ecc4e9b7444a89a13c493cb563fcd",
          "label":"模拟考试1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":440},
            "size":{
              "width":380,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e5e17e710944497a79cdce8a8b3c0fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":440},
                "size":{
                  "width":380,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"返回在线",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看试卷",
                      "target":{
                        "targetType":"page",
                        "url":"查看试卷.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"072519e33890450f880b726429085444",
          "label":"模拟考试1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":510},
            "size":{
              "width":380,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af3d95e69fa947d69d042185567959bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":510},
                "size":{
                  "width":380,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"返回在线",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 历史成绩",
                      "target":{
                        "targetType":"page",
                        "url":"历史成绩.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc654f35f13e4cc2a453a615dd7a840f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1CACFA},
            "location":{
              "x":157,
              "y":150},
            "size":{
              "width":73,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d091b4a0cb4043869cc7c778c2bbfc4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1CACFA},
                "location":{
                  "x":157,
                  "y":150},
                "size":{
                  "width":73,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考试成绩/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "366f87c55af64ab18a151fefac675905":{
      "scriptId":"u0"},
    "1e20316f4cfd4189826e9b34708fe669":{
      "scriptId":"u1"},
    "f6d4a4dd8feb41b688afb9c73e5d8ad2":{
      "scriptId":"u2"},
    "35e28676e7cb483aa56535d803ff374e":{
      "scriptId":"u3"},
    "881a57147c924648afdbe4adb1a2d313":{
      "scriptId":"u4"},
    "1b7afd3e248c4526ad15e42268596664":{
      "scriptId":"u5"},
    "bc7ecc4e9b7444a89a13c493cb563fcd":{
      "scriptId":"u6"},
    "3e5e17e710944497a79cdce8a8b3c0fa":{
      "scriptId":"u7"},
    "072519e33890450f880b726429085444":{
      "scriptId":"u8"},
    "af3d95e69fa947d69d042185567959bc":{
      "scriptId":"u9"},
    "cc654f35f13e4cc2a453a615dd7a840f":{
      "scriptId":"u10"},
    "d091b4a0cb4043869cc7c778c2bbfc4d":{
      "scriptId":"u11"}}});