$axure.loadCurrentPage({
  "url":"自助移车.html",
  "generationDate":new Date(1503973157140.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"jvbao",
"yiche",
"mianfenquan"],
  "page":{
    "packageId":"d37187947ac84b2c89d112d1015d9df2",
    "type":"Axure:Page",
    "name":"自助移车",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1<br> (If 值于 yiche 等于 &quot;1&quot;)",
            "isNewIfGroup":false,
            "condition":{
              "exprType":"binaryOp",
              "op":"==",
              "leftExpr":{
                "exprType":"fcall",
                "functionName":"GetGlobalVariableValue",
                "arguments":[{
                    "exprType":"globalVariableLiteral",
                    "variableName":"yiche"}]},
              "rightExpr":{
                "exprType":"stringLiteral",
                "value":"1",
                "stos":[]}},
            "actions":[{
                "action":"setPanelState",
                "description":"设置 (动态面板) to 会员二维码",
                "panelsToStates":[{
                    "panelPath":["2bdbec9fe75c410795c262b6034a8078"],
                    "stateInfo":{
                      "setStateType":"diagram",
                      "stateNumber":2,
                      "stateValue":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]},
                      "loop":false,
                      "showWhenSet":false,
                      "options":{
                        "compress":false}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"2bdbec9fe75c410795c262b6034a8078",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":370,
              "height":650}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"e42b308e9d04475eb4d0d6ad5230c4d4",
              "label":"移车",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0ca3d2692a21495791a4c1286fb2f957",
                  "label":"",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":647}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6fb2b9b3253b44a5a834de2013dcfdcb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":375,
                          "height":647}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/自助移车/u1.png"}},
{
                  "id":"bda3e138d7bb404a9fa89056700e1218",
                  "label":"移车卡按钮",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":185,
                      "y":50},
                    "size":{
                      "width":190,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"342fa97ea44b441ca396ccd5a7293f5f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":185,
                          "y":50},
                        "size":{
                          "width":190,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"非E会员",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 非会员二维码",
                              "panelsToStates":[{
                                  "panelPath":["2bdbec9fe75c410795c262b6034a8078"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]},
{
                          "description":"E会员",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 会员二维码",
                              "panelsToStates":[{
                                  "panelPath":["2bdbec9fe75c410795c262b6034a8078"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"setFunction",
                              "description":"设置 值于 yiche = &quot;2&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetGlobalVariableValue",
                                    "arguments":[{
                                        "exprType":"globalVariableLiteral",
                                        "variableName":"yiche"},
{
                                        "exprType":"stringLiteral",
                                        "value":"2",
                                        "stos":[]}]}]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c4b1d86b6025415ba453d0bc89e1de1e",
                  "label":"提交移车申请按钮",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":560},
                    "size":{
                      "width":370,
                      "height":70},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c67b6492825b40e7aeb5ee3beb3d3dc8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":560},
                        "size":{
                          "width":370,
                          "height":70},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 提示,<br>蒙版,<br>确定按钮,<br>关闭按钮",
                              "objectsToFades":[{
                                  "objectPath":["3f00010be0ee481297291213592375f9"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["e537a46de4d145a7b91b7ead3d6d0cb8"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["bd9c341d1d674349964a02020091b086"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["ab70798f3931464695cdd796088c508d"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示/隐藏部件",
                              "objectsToFades":[]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"aa3c6fc1ca6c4ea68e045924d750aa76",
                  "label":"加号按钮",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":80,
                      "y":430},
                    "size":{
                      "width":80,
                      "height":70},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"abe28b5e945d4e5f8c98493cfcdcd08c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":80,
                          "y":430},
                        "size":{
                          "width":80,
                          "height":70},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 拍照,<br>取消按钮",
                              "objectsToFades":[{
                                  "objectPath":["8ae15067dc564401b7ab8b14fc2d80b5"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["777f283d6f8e4e8da1da2e7f8c28dec5"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示/隐藏部件",
                              "objectsToFades":[]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e537a46de4d145a7b91b7ead3d6d0cb8",
                  "label":"蒙版",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "opacity":"0.7",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000},
                    "size":{
                      "width":375,
                      "height":647},
                    "visible":false,
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"22be29f2eae7428eb4bda581810e687b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "opacity":"0.7",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF000000},
                        "size":{
                          "width":375,
                          "height":647},
                        "visible":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/举报资料/蒙版_u8.png"}},
{
                  "id":"ab70798f3931464695cdd796088c508d",
                  "label":"关闭按钮",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":333,
                      "y":177},
                    "size":{
                      "width":29,
                      "height":26},
                    "visible":false,
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e0f22b1aabca4726ba11437e962f927f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":333,
                          "y":177},
                        "size":{
                          "width":29,
                          "height":26},
                        "visible":false,
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 蒙版,<br>提示,<br>关闭按钮,<br>确定按钮",
                              "objectsToFades":[{
                                  "objectPath":["e537a46de4d145a7b91b7ead3d6d0cb8"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["3f00010be0ee481297291213592375f9"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["ab70798f3931464695cdd796088c508d"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["bd9c341d1d674349964a02020091b086"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示/隐藏部件",
                              "objectsToFades":[]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/自助移车/关闭按钮_u11.png"}},
{
                  "id":"8ae15067dc564401b7ab8b14fc2d80b5",
                  "label":"拍照",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "size":{
                      "width":375,
                      "height":647},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d11f0b677d3f4075a48dcc38e5e1d656",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "size":{
                          "width":375,
                          "height":647},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/自助移车/拍照_u13.jpg"}},
{
                  "id":"777f283d6f8e4e8da1da2e7f8c28dec5",
                  "label":"取消按钮",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":5,
                      "y":596},
                    "size":{
                      "width":370,
                      "height":51},
                    "visible":false,
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4b279495174a4f3ca6c536ce2e3e2974",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":5,
                          "y":596},
                        "size":{
                          "width":370,
                          "height":51},
                        "visible":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 取消按钮,<br>拍照",
                              "objectsToFades":[{
                                  "objectPath":["777f283d6f8e4e8da1da2e7f8c28dec5"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["8ae15067dc564401b7ab8b14fc2d80b5"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示/隐藏部件",
                              "objectsToFades":[]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3f00010be0ee481297291213592375f9",
                  "label":"提示",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":10,
                      "y":213},
                    "size":{
                      "width":349,
                      "height":239},
                    "visible":false,
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b100de2387f84cefa2137eec310b1532",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":10,
                          "y":213},
                        "size":{
                          "width":349,
                          "height":239},
                        "visible":false,
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/自助移车/提示_u17.png"}},
{
                  "id":"bd9c341d1d674349964a02020091b086",
                  "label":"确定按钮",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":30,
                      "y":380},
                    "size":{
                      "width":320,
                      "height":50},
                    "visible":false,
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1105eee1e8e84e7795e8dd178fde8de3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":30,
                          "y":380},
                        "size":{
                          "width":320,
                          "height":50},
                        "visible":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 移车完成",
                              "target":{
                                "targetType":"page",
                                "url":"移车完成.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d79acfe28dc6416eb5781905cc2fa190",
                  "label":"加号按钮",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":100},
                    "size":{
                      "width":265,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"42a51fa73b8f401a809a19df61d7fcb8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":100},
                        "size":{
                          "width":265,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 扫码,<br>扫码",
                              "objectsToFades":[{
                                  "objectPath":["ec6fe2b59b524d6faab60f491e20e17e"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["e232cff3112649059829eb3ca44643ea"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e232cff3112649059829eb3ca44643ea",
                  "label":"扫码",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":0,
                      "y":45},
                    "size":{
                      "width":375,
                      "height":479},
                    "visible":false,
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0f07c2d023f44a23a1de87d80cbba313",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":0,
                          "y":45},
                        "size":{
                          "width":375,
                          "height":479},
                        "visible":false,
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/自助移车/扫码_u23.png"}},
{
                  "id":"ec6fe2b59b524d6faab60f491e20e17e",
                  "label":"扫码",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF424342},
                    "location":{
                      "x":0,
                      "y":521},
                    "size":{
                      "width":375,
                      "height":129},
                    "visible":false,
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a33e0a432be4da6b6685ed3c7957147",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF424342},
                        "location":{
                          "x":0,
                          "y":521},
                        "size":{
                          "width":375,
                          "height":129},
                        "visible":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/自助移车/扫码_u25.png"}}]},
{
              "id":"bd0ab8c71ebc4922a50df7a00863294f",
              "label":"会员二维码",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3b1feac470c443528d1b0bd809b56623",
                  "label":"",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":647}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cedd7fa35ccb49b5b8b7370a601b32c5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":375,
                          "height":647}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/自助移车/u27.png"}},
{
                  "id":"db826bef0d344a1fb013d2c86cd153d9",
                  "label":"一键移车按钮",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":50},
                    "size":{
                      "width":190,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f4ede639abf7483d99cd22061f38c559",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":50},
                        "size":{
                          "width":190,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 移车",
                              "panelsToStates":[{
                                  "panelPath":["2bdbec9fe75c410795c262b6034a8078"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d91fbedc56d74cc2a997e3808d6ea435",
                  "label":"移车卡生成页面",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":44},
                    "size":{
                      "width":375,
                      "height":603},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"32764223b5a245458700317be91caec9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":44},
                        "size":{
                          "width":375,
                          "height":603},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onShow":{
                      "description":"OnShow",
                      "cases":[{
                          "description":"用例 1<br> (If 值于 yiche 等于 &quot;1&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetGlobalVariableValue",
                              "arguments":[{
                                  "exprType":"globalVariableLiteral",
                                  "variableName":"yiche"}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]}},
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 移车卡生成页面",
                              "objectsToFades":[{
                                  "objectPath":["d91fbedc56d74cc2a997e3808d6ea435"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "images":{
                    "normal~":"images/自助移车/移车卡生成页面_u31.png"}},
{
                  "id":"03ba5f23ac784296872db3a43f62c7f5",
                  "label":"返回",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"987cfecfd86a42caa9cf639fe560d1b3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"个人中心<br> (If 值于 yiche 等于 &quot;1&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetGlobalVariableValue",
                              "arguments":[{
                                  "exprType":"globalVariableLiteral",
                                  "variableName":"yiche"}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]}},
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 个人中心",
                              "target":{
                                "targetType":"page",
                                "url":"个人中心.html",
                                "includeVariables":true},
                              "linkType":"current"}]},
{
                          "description":"返回移车<br> (Else If 值于 yiche 等于 &quot;2&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetGlobalVariableValue",
                              "arguments":[{
                                  "exprType":"globalVariableLiteral",
                                  "variableName":"yiche"}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"2",
                              "stos":[]}},
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 自助移车",
                              "target":{
                                "targetType":"page",
                                "url":"自助移车.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"3272e3556ac3491a98715219394338ba",
              "label":"非会员二维码",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f17cf152f2994be58e50f76a01acfa44",
                  "label":"",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":647}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6cfe23523ef8462298de5dabf31ba73b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":375,
                          "height":647}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/自助移车/u27.png"}},
{
                  "id":"1fbacd8a3fc84be2a476c3c4ff6303f1",
                  "label":"遮挡",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF3F5F6},
                    "location":{
                      "x":0,
                      "y":100},
                    "size":{
                      "width":370,
                      "height":520},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e5157e02c15c4f2c9f9e242734a15eaf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF3F5F6},
                        "location":{
                          "x":0,
                          "y":100},
                        "size":{
                          "width":370,
                          "height":520},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/自助移车/遮挡_u37.png"}},
{
                  "id":"4f38f71f28f24962a27d1273164b987d",
                  "label":"一键移车按钮",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":50},
                    "size":{
                      "width":190,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4c707ee45c9b40749e181cd0091a571f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":50},
                        "size":{
                          "width":190,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 移车",
                              "panelsToStates":[{
                                  "panelPath":["2bdbec9fe75c410795c262b6034a8078"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bcb99d68c2b24bd0afe1cdb9c8e6f728",
                  "label":"返回",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0x333333,
                      "opacity":0},
                    "opacity":"0",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d2e65c85e96c4ada89723dfa953aa0c9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0x333333,
                          "opacity":0},
                        "opacity":"0",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 个人中心",
                              "target":{
                                "targetType":"page",
                                "url":"个人中心.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8f226c8ed5214bd981d1326814fbc424",
                  "label":"文字",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微軟正黑體 Bold', '微軟正黑體'",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":18,
                      "y":184},
                    "size":{
                      "width":332,
                      "height":66}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"beb21e3d0183481abf0bf8408f7b5302",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微軟正黑體 Bold', '微軟正黑體'",
                        "horizontalAlignment":"center",
                        "location":{
                          "x":18,
                          "y":184},
                        "size":{
                          "width":332,
                          "height":66}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"967320cefefe42d29349de07b6b3be40",
                  "label":"会员认证",
                  "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微軟正黑體 Regular', '微軟正黑體'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF2284D3},
                    "location":{
                      "x":84,
                      "y":250},
                    "size":{
                      "width":200,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE5E5E5},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d95d1fb282354a4e9fe7717a23c6b72c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2bdbec9fe75c410795c262b6034a8078",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微軟正黑體 Regular', '微軟正黑體'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF2284D3},
                        "location":{
                          "x":84,
                          "y":250},
                        "size":{
                          "width":200,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE5E5E5},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onShow":{
                      "description":"OnShow",
                      "cases":[{
                          "description":"用例 1<br> (If 值于 yiche 等于 &quot;2&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetGlobalVariableValue",
                              "arguments":[{
                                  "exprType":"globalVariableLiteral",
                                  "variableName":"yiche"}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"2",
                              "stos":[]}},
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 会员认证,<br>文字,<br>返回",
                              "objectsToFades":[{
                                  "objectPath":["967320cefefe42d29349de07b6b3be40"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["8f226c8ed5214bd981d1326814fbc424"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["bcb99d68c2b24bd0afe1cdb9c8e6f728"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "images":{
                    "normal~":"images/自助移车/会员认证_u45.png"}}]}]},
{
          "id":"bfc26b0fd9084d9caabc47e63a559cda",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":90,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f286452819e04cd29f6c27f13d0c22af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":90,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "2bdbec9fe75c410795c262b6034a8078":{
      "scriptId":"u0"},
    "0ca3d2692a21495791a4c1286fb2f957":{
      "scriptId":"u1"},
    "6fb2b9b3253b44a5a834de2013dcfdcb":{
      "scriptId":"u2"},
    "bda3e138d7bb404a9fa89056700e1218":{
      "scriptId":"u3"},
    "342fa97ea44b441ca396ccd5a7293f5f":{
      "scriptId":"u4"},
    "c4b1d86b6025415ba453d0bc89e1de1e":{
      "scriptId":"u5"},
    "c67b6492825b40e7aeb5ee3beb3d3dc8":{
      "scriptId":"u6"},
    "aa3c6fc1ca6c4ea68e045924d750aa76":{
      "scriptId":"u7"},
    "abe28b5e945d4e5f8c98493cfcdcd08c":{
      "scriptId":"u8"},
    "e537a46de4d145a7b91b7ead3d6d0cb8":{
      "scriptId":"u9"},
    "22be29f2eae7428eb4bda581810e687b":{
      "scriptId":"u10"},
    "ab70798f3931464695cdd796088c508d":{
      "scriptId":"u11"},
    "e0f22b1aabca4726ba11437e962f927f":{
      "scriptId":"u12"},
    "8ae15067dc564401b7ab8b14fc2d80b5":{
      "scriptId":"u13"},
    "d11f0b677d3f4075a48dcc38e5e1d656":{
      "scriptId":"u14"},
    "777f283d6f8e4e8da1da2e7f8c28dec5":{
      "scriptId":"u15"},
    "4b279495174a4f3ca6c536ce2e3e2974":{
      "scriptId":"u16"},
    "3f00010be0ee481297291213592375f9":{
      "scriptId":"u17"},
    "b100de2387f84cefa2137eec310b1532":{
      "scriptId":"u18"},
    "bd9c341d1d674349964a02020091b086":{
      "scriptId":"u19"},
    "1105eee1e8e84e7795e8dd178fde8de3":{
      "scriptId":"u20"},
    "d79acfe28dc6416eb5781905cc2fa190":{
      "scriptId":"u21"},
    "42a51fa73b8f401a809a19df61d7fcb8":{
      "scriptId":"u22"},
    "e232cff3112649059829eb3ca44643ea":{
      "scriptId":"u23"},
    "0f07c2d023f44a23a1de87d80cbba313":{
      "scriptId":"u24"},
    "ec6fe2b59b524d6faab60f491e20e17e":{
      "scriptId":"u25"},
    "7a33e0a432be4da6b6685ed3c7957147":{
      "scriptId":"u26"},
    "3b1feac470c443528d1b0bd809b56623":{
      "scriptId":"u27"},
    "cedd7fa35ccb49b5b8b7370a601b32c5":{
      "scriptId":"u28"},
    "db826bef0d344a1fb013d2c86cd153d9":{
      "scriptId":"u29"},
    "f4ede639abf7483d99cd22061f38c559":{
      "scriptId":"u30"},
    "d91fbedc56d74cc2a997e3808d6ea435":{
      "scriptId":"u31"},
    "32764223b5a245458700317be91caec9":{
      "scriptId":"u32"},
    "03ba5f23ac784296872db3a43f62c7f5":{
      "scriptId":"u33"},
    "987cfecfd86a42caa9cf639fe560d1b3":{
      "scriptId":"u34"},
    "f17cf152f2994be58e50f76a01acfa44":{
      "scriptId":"u35"},
    "6cfe23523ef8462298de5dabf31ba73b":{
      "scriptId":"u36"},
    "1fbacd8a3fc84be2a476c3c4ff6303f1":{
      "scriptId":"u37"},
    "e5157e02c15c4f2c9f9e242734a15eaf":{
      "scriptId":"u38"},
    "4f38f71f28f24962a27d1273164b987d":{
      "scriptId":"u39"},
    "4c707ee45c9b40749e181cd0091a571f":{
      "scriptId":"u40"},
    "bcb99d68c2b24bd0afe1cdb9c8e6f728":{
      "scriptId":"u41"},
    "d2e65c85e96c4ada89723dfa953aa0c9":{
      "scriptId":"u42"},
    "8f226c8ed5214bd981d1326814fbc424":{
      "scriptId":"u43"},
    "beb21e3d0183481abf0bf8408f7b5302":{
      "scriptId":"u44"},
    "967320cefefe42d29349de07b6b3be40":{
      "scriptId":"u45"},
    "d95d1fb282354a4e9fe7717a23c6b72c":{
      "scriptId":"u46"},
    "bfc26b0fd9084d9caabc47e63a559cda":{
      "scriptId":"u47"},
    "f286452819e04cd29f6c27f13d0c22af":{
      "scriptId":"u48"}}});