$axure.loadCurrentPage({
  "url":"驾考在线学习.html",
  "generationDate":new Date(1503973157771.84),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"jvbao",
"yiche",
"mianfenquan"],
  "page":{
    "packageId":"60069527f48b46dd8120dfb1728599a4",
    "type":"Axure:Page",
    "name":"驾考在线学习",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1b2bcd0e76894e7ab1b9ba6d862da009",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":647},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bc8208c3f344a23b0c7db0591ad85c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":647},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/驾考在线学习/u0.png"}},
{
          "id":"2b1d07563a564a6c88c4161cb0b6c5bc",
          "label":"模拟考试1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":18,
              "y":56},
            "size":{
              "width":340,
              "height":94},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ef3f4fc42f748faaa62614c2337a3da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":18,
                  "y":56},
                "size":{
                  "width":340,
                  "height":94},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 模拟考试",
                      "target":{
                        "targetType":"page",
                        "url":"模拟考试.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20e6104f20be4ed991edb3892e0b6f3a",
          "label":"历史成绩",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":18,
              "y":280},
            "size":{
              "width":340,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21a63e1986c94704b21965e3af6a38ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":18,
                  "y":280},
                "size":{
                  "width":340,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"历史成绩",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 历史成绩",
                      "target":{
                        "targetType":"page",
                        "url":"历史成绩.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bdef0fef6b234834b54c7d321f825963",
          "label":"我的错题",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":18,
              "y":390},
            "size":{
              "width":340,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"367ad80e27c644298335de44d0e72cf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":18,
                  "y":390},
                "size":{
                  "width":340,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"我的错题",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的错题",
                      "target":{
                        "targetType":"page",
                        "url":"我的错题.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ac789d21a5245fcb45afb821fa18732",
          "label":"模拟考试1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":18,
              "y":170},
            "size":{
              "width":340,
              "height":94},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c623bf5b1e849ccbd2bb6986548b76f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":18,
                  "y":170},
                "size":{
                  "width":340,
                  "height":94},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 模拟考试",
                      "target":{
                        "targetType":"page",
                        "url":"模拟考试.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8e10d6d633147a5a9b0444eafd8ad14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":90,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db863b6164754891b5f1f2967774b9c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":90,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1b2bcd0e76894e7ab1b9ba6d862da009":{
      "scriptId":"u0"},
    "6bc8208c3f344a23b0c7db0591ad85c3":{
      "scriptId":"u1"},
    "2b1d07563a564a6c88c4161cb0b6c5bc":{
      "scriptId":"u2"},
    "2ef3f4fc42f748faaa62614c2337a3da":{
      "scriptId":"u3"},
    "20e6104f20be4ed991edb3892e0b6f3a":{
      "scriptId":"u4"},
    "21a63e1986c94704b21965e3af6a38ee":{
      "scriptId":"u5"},
    "bdef0fef6b234834b54c7d321f825963":{
      "scriptId":"u6"},
    "367ad80e27c644298335de44d0e72cf8":{
      "scriptId":"u7"},
    "5ac789d21a5245fcb45afb821fa18732":{
      "scriptId":"u8"},
    "0c623bf5b1e849ccbd2bb6986548b76f":{
      "scriptId":"u9"},
    "c8e10d6d633147a5a9b0444eafd8ad14":{
      "scriptId":"u10"},
    "db863b6164754891b5f1f2967774b9c9":{
      "scriptId":"u11"}}});