$axure.loadCurrentPage({
  "url":"取消预约输入.html",
  "generationDate":new Date(1503998490501.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"jvbao",
"yiche",
"mianfenquan"],
  "page":{
    "packageId":"e4848355f7b6491d8a83f8052e8088a5",
    "type":"Axure:Page",
    "name":"取消预约输入",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"42142cc8a52e456db0894a7f457aee97",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":642}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0e605b608b14109865682a1f34e63d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":642}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/取消预约输入/u0.png"}},
{
          "id":"9de570c9e0cd40e6bdbcc86c13e51e10",
          "label":"返回办理页",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":12.5,
              "y":168},
            "size":{
              "width":350,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0659ed72e9924539a008242c965624a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":12.5,
                  "y":168},
                "size":{
                  "width":350,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 取消预约确认",
                      "target":{
                        "targetType":"page",
                        "url":"取消预约确认_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7918daef023846ce986f5783adf20174",
          "label":"返回办理页",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":150,
              "y":248},
            "size":{
              "width":80,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9d00f8094854d08840c98fd990e932f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":150,
                  "y":248},
                "size":{
                  "width":80,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 六年免检办理及预约",
                      "target":{
                        "targetType":"page",
                        "url":"六年免检办理及预约.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48ba22cf7ac64d569e8c943032645190",
          "label":"返回办理页",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":110,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72f79b89856543da9ba52ff9d97a73a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":110,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 六年免检办理及预约",
                      "target":{
                        "targetType":"page",
                        "url":"六年免检办理及预约.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "42142cc8a52e456db0894a7f457aee97":{
      "scriptId":"u0"},
    "e0e605b608b14109865682a1f34e63d3":{
      "scriptId":"u1"},
    "9de570c9e0cd40e6bdbcc86c13e51e10":{
      "scriptId":"u2"},
    "0659ed72e9924539a008242c965624a9":{
      "scriptId":"u3"},
    "7918daef023846ce986f5783adf20174":{
      "scriptId":"u4"},
    "a9d00f8094854d08840c98fd990e932f":{
      "scriptId":"u5"},
    "48ba22cf7ac64d569e8c943032645190":{
      "scriptId":"u6"},
    "72f79b89856543da9ba52ff9d97a73a6":{
      "scriptId":"u7"}}});