$axure.loadCurrentPage({
  "url":"自我测试_1.html",
  "generationDate":new Date(1503973160103.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"jvbao",
"yiche",
"mianfenquan"],
  "page":{
    "packageId":"bc1405dc15ae4962abb6bbd44b74b559",
    "type":"Axure:Page",
    "name":"自我测试",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ca4c339cc6884361a84bcb5413f27d9d",
          "label":"答题前",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":647}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fc2634b725b448b83b6cbd406c0e91c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":647}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/模拟考试/题目_u0.png"}},
{
          "id":"f27431d0aa2843aa9717a54e9b52bbea",
          "label":"显示答案",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "size":{
              "width":375,
              "height":647},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5aefe592ddc34c50829e7c515f6f2217",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "size":{
                  "width":375,
                  "height":647},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 进入视频学习,<br>选择答案,<br>返回上页2,<br>显示答案,<br>答题前,<br>This",
                      "objectsToFades":[{
                          "objectPath":["e6e0881ffcf146e79bb62b4db21625a4"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["e24604b75f52486383038586aa815826"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2b836a814bb24e72b73ecea9c1aa2b04"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f27431d0aa2843aa9717a54e9b52bbea"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ca4c339cc6884361a84bcb5413f27d9d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f27431d0aa2843aa9717a54e9b52bbea"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/模拟考试/答案_u6.png"}},
{
          "id":"2b836a814bb24e72b73ecea9c1aa2b04",
          "label":"返回上页2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":120,
              "height":40},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35a8cec18d614fa8840b737a8e3fe0f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":120,
                  "height":40},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 学习视频",
                      "target":{
                        "targetType":"page",
                        "url":"学习视频_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e24604b75f52486383038586aa815826",
          "label":"选择答案",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":0,
              "y":280},
            "size":{
              "width":380,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb8bec73033c41c4814c972eded745c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":0,
                  "y":280},
                "size":{
                  "width":380,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 返回上页2,<br>显示答案,<br>进入视频学习",
                      "objectsToFades":[{
                          "objectPath":["2b836a814bb24e72b73ecea9c1aa2b04"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f27431d0aa2843aa9717a54e9b52bbea"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["e6e0881ffcf146e79bb62b4db21625a4"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6e0881ffcf146e79bb62b4db21625a4",
          "label":"进入视频学习",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":361,
              "height":647},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36c9537b547b4c6a954b3626cfc76967",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":361,
                  "height":647},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (形状),<br>(形状),<br>(形状),<br>确认按钮,<br>蒙版,<br>(水平线),<br>(垂直线)",
                      "objectsToFades":[{
                          "objectPath":["c51275adc5ce42f1a94a90528bd82bd8"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["1ee29b4b617d48b1825436a7e1e6b558"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6985dc40460d4427a8f57b1ceb56cc46"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["fc01d974cde44328baae4a7532730a95"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0135a3378c6349039ad6faf99705e88c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["490180b0a9ba48c39ab3b25c37bbe670"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["a077aae4fe5d4a5aba07f8f84a57c898"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 进入视频学习,<br>选择答案,<br>返回上页2,<br>显示答案,<br>答题前,<br>This,<br>返回上页",
                      "objectsToFades":[{
                          "objectPath":["e6e0881ffcf146e79bb62b4db21625a4"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["e24604b75f52486383038586aa815826"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2b836a814bb24e72b73ecea9c1aa2b04"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f27431d0aa2843aa9717a54e9b52bbea"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ca4c339cc6884361a84bcb5413f27d9d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["e6e0881ffcf146e79bb62b4db21625a4"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["5ed03da287354937a49843454822918d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ed03da287354937a49843454822918d",
          "label":"返回上页",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":120,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5414563855074ee4a98ee1b657c16449",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":120,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 满分学习须知",
                      "target":{
                        "targetType":"page",
                        "url":"满分学习须知.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0135a3378c6349039ad6faf99705e88c",
          "label":"蒙版",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.7",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":1050,
              "y":43},
            "size":{
              "width":375,
              "height":647},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfc70955bfa74f8194d65473aff9e2fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.7",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":1050,
                  "y":43},
                "size":{
                  "width":375,
                  "height":647},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报资料/蒙版_u8.png"}},
{
          "id":"fc01d974cde44328baae4a7532730a95",
          "label":"确认按钮",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "verticalAlignment":"top",
            "lineSpacing":"28px",
            "paddingTop":"15",
            "location":{
              "x":1084,
              "y":256},
            "size":{
              "width":306,
              "height":92},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE5E5E5},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71ef2926b77543bfaf068122796286ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "verticalAlignment":"top",
                "lineSpacing":"28px",
                "paddingTop":"15",
                "location":{
                  "x":1084,
                  "y":256},
                "size":{
                  "width":306,
                  "height":92},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE5E5E5},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/自我测试/确认按钮_u14.png"}},
{
          "id":"6985dc40460d4427a8f57b1ceb56cc46",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":1240,
              "y":303},
            "size":{
              "width":150,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47190c5ea758477a96bf8421abfb7f2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":1240,
                  "y":303},
                "size":{
                  "width":150,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我测试/u16.png"}},
{
          "id":"1ee29b4b617d48b1825436a7e1e6b558",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1134,
              "y":265},
            "size":{
              "width":215,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6186d8f5f6f43fdbde01222339153a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1134,
                  "y":265},
                "size":{
                  "width":215,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学习视频/u8.png"}},
{
          "id":"c51275adc5ce42f1a94a90528bd82bd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":1084,
              "y":303},
            "size":{
              "width":146,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fee10694ad84538a3546bad18851113",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":1084,
                  "y":303},
                "size":{
                  "width":146,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 满分学习须知",
                      "target":{
                        "targetType":"page",
                        "url":"满分学习须知.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/自我测试/u20.png"}},
{
          "id":"490180b0a9ba48c39ab3b25c37bbe670",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1102,
              "y":297},
            "size":{
              "width":278,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE5E5E5}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/自我测试/u22_line.png"}},
{
          "id":"a077aae4fe5d4a5aba07f8f84a57c898",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1232,
              "y":303},
            "size":{
              "width":10,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE5E5E5}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/自我测试/u23_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ca4c339cc6884361a84bcb5413f27d9d":{
      "scriptId":"u0"},
    "1fc2634b725b448b83b6cbd406c0e91c":{
      "scriptId":"u1"},
    "f27431d0aa2843aa9717a54e9b52bbea":{
      "scriptId":"u2"},
    "5aefe592ddc34c50829e7c515f6f2217":{
      "scriptId":"u3"},
    "2b836a814bb24e72b73ecea9c1aa2b04":{
      "scriptId":"u4"},
    "35a8cec18d614fa8840b737a8e3fe0f4":{
      "scriptId":"u5"},
    "e24604b75f52486383038586aa815826":{
      "scriptId":"u6"},
    "cb8bec73033c41c4814c972eded745c2":{
      "scriptId":"u7"},
    "e6e0881ffcf146e79bb62b4db21625a4":{
      "scriptId":"u8"},
    "36c9537b547b4c6a954b3626cfc76967":{
      "scriptId":"u9"},
    "5ed03da287354937a49843454822918d":{
      "scriptId":"u10"},
    "5414563855074ee4a98ee1b657c16449":{
      "scriptId":"u11"},
    "0135a3378c6349039ad6faf99705e88c":{
      "scriptId":"u12"},
    "bfc70955bfa74f8194d65473aff9e2fb":{
      "scriptId":"u13"},
    "fc01d974cde44328baae4a7532730a95":{
      "scriptId":"u14"},
    "71ef2926b77543bfaf068122796286ea":{
      "scriptId":"u15"},
    "6985dc40460d4427a8f57b1ceb56cc46":{
      "scriptId":"u16"},
    "47190c5ea758477a96bf8421abfb7f2a":{
      "scriptId":"u17"},
    "1ee29b4b617d48b1825436a7e1e6b558":{
      "scriptId":"u18"},
    "b6186d8f5f6f43fdbde01222339153a5":{
      "scriptId":"u19"},
    "c51275adc5ce42f1a94a90528bd82bd8":{
      "scriptId":"u20"},
    "0fee10694ad84538a3546bad18851113":{
      "scriptId":"u21"},
    "490180b0a9ba48c39ab3b25c37bbe670":{
      "scriptId":"u22"},
    "a077aae4fe5d4a5aba07f8f84a57c898":{
      "scriptId":"u23"}}});